"""FrameTree registry - nested, child codes relative to their parent.

    "Name": (anchor, {children})    top level (anchor tail is always empty)
    "Name": anchor                  top level, no children
    "Child": code                   leaf
    "Child": (code, {children})     branch

Nesting follows the code path, which is authoritative; the dotted labels in
frame_aliases.py only supplied node names.  Anchor names resolve through
frame_names.py (NAME_TO_HASH).

Generated from frame_aliases.py - do not hand-edit.
"""

REGISTRY: dict = {
    'Hero1Window': ('AgentCommander0', {
        'FightButton': 0,
        'GuardButton': 1,
        'AvoidButton': 2,
        'AvatarFrame': (3, {
            'Content': 0,
            'Content1': 1,
        }),
        'BuffFrame': 4,
        'SkillBar': (5, {
            'Skill1': 0,
            'Skill2': 1,
            'Skill3': 2,
            'Skill4': 3,
            'Skill5': 4,
            'Skill6': 5,
            'Skill7': 6,
            'Skill8': 7,
        }),
        'EnergyBar': 6,
        'HealthBar': 7,
        'TargetButton': 8,
    }),
    'Hero2Window': ('AgentCommander1', {
        'FightButton': 0,
        'GuardButton': 1,
        'AvoidButton': 2,
        'AvatarFrame': 3,
        'BuffFrame': 4,
        'SkillBar': (5, {
            'Skill1': 0,
            'Skill2': 1,
            'Skill3': 2,
            'Skill4': 3,
            'Skill5': 4,
            'Skill6': 5,
            'Skill7': 6,
            'Skill8': 7,
        }),
        'EnergyBar': 6,
        'HealthBar': 7,
        'TargetButton': 8,
    }),
    'Hero3Window': ('AgentCommander2', {
        'FightButton': 0,
        'GuardButton': 1,
        'AvoidButton': 2,
        'AvatarFrame': 3,
        'BuffFrame': 4,
        'SkillBar': (5, {
            'Skill1': 0,
            'Skill2': 1,
            'Skill3': 2,
            'Skill4': 3,
            'Skill5': 4,
            'Skill6': 5,
            'Skill7': 6,
            'Skill8': 7,
        }),
        'EnergyBar': 6,
        'HealthBar': 7,
        'TargetButton': 8,
    }),
    'Hero4Window': ('AgentCommander3', {
        'FightButton': 0,
        'GuardButton': 1,
        'AvoidButton': 2,
        'AvatarFrame': 3,
        'BuffFrame': 4,
        'SkillBar': (5, {
            'Skill1': 0,
            'Skill2': 1,
            'Skill3': 2,
            'Skill4': 3,
            'Skill5': 4,
            'Skill6': 5,
            'Skill7': 6,
            'Skill8': 7,
        }),
        'EnergyBar': 6,
        'HealthBar': 7,
        'TargetButton': 8,
    }),
    'Hero5Window': ('AgentCommander4', {
        'FightButton': 0,
        'GuardButton': 1,
        'AvoidButton': 2,
        'AvatarFrame': 3,
        'BuffFrame': 4,
        'SkillBar': (5, {
            'Skill1': 0,
            'Skill2': 1,
            'Skill3': 2,
            'Skill4': 3,
            'Skill5': 4,
            'Skill6': 5,
            'Skill7': 6,
            'Skill8': 7,
        }),
        'EnergyBar': 6,
        'HealthBar': 7,
        'TargetButton': 8,
    }),
    'Hero6Window': ('AgentCommander5', {
        'FightButton': 0,
        'GuardButton': 1,
        'AvoidButton': 2,
        'AvatarFrame': 3,
        'BuffFrame': 4,
        'SkillBar': (5, {
            'Skill1': 0,
            'Skill2': 1,
            'Skill3': 2,
            'Skill4': 3,
            'Skill5': 4,
            'Skill6': 5,
            'Skill7': 6,
            'Skill8': 7,
        }),
        'EnergyBar': 6,
        'HealthBar': 7,
        'TargetButton': 8,
    }),
    'Hero7Window': ('AgentCommander6', {
        'FightButton': 0,
        'GuardButton': 1,
        'AvoidButton': 2,
        'AvatarFrame': 3,
        'BuffFrame': 4,
        'SkillBar': (5, {
            'Skill1': 0,
            'Skill2': 1,
            'Skill3': 2,
            'Skill4': 3,
            'Skill5': 4,
            'Skill6': 5,
            'Skill7': 6,
            'Skill8': 7,
        }),
        'EnergyBar': 6,
        'HealthBar': 7,
        'TargetButton': 8,
    }),
    'CharacterCreateCharacterAppearanceFrame': 'Appearance',
    'HeroWindow': ('Attributes', {
        'Info': (0, {
            'XpBar': 0,
            'Level': 1,
            'SkillPoints': 2,
        }),
        'CharacterAvatar': 1,
        'Tabs': (2, {
            'Content': (0, {
                'Inner': (0, {
                    'Account': (0, {
                        'Name': 1,
                        'TournamentInfo': 2,
                        'TournamentData': (4, {
                            'TournamentLabel': 0,
                            'RewardPoints': 1,
                        }),
                    }),
                }),
            }),
            'Content2': (1, {
                'Inner': (0, {
                    'Factions': (0, {
                        'Bars': (0, {
                            'Kurzick': 0,
                            'Luxon': 1,
                            'Balthazar': 2,
                            'Imperial': 3,
                        }),
                    }),
                }),
            }),
            'Content3': (2, {
                'Inner': (0, {
                    'Titles': (0, {
                        'Area': (0, {
                            'TyrianExploration': 1,
                            'CanthaExplorationTitleTrack': 2,
                            'KurzickSupporter': 5,
                            'Drunkard': 7,
                            'Survivor': 9,
                            'Gwamm': 10,
                            'ProtectorofTyria': 13,
                            'ProtectorofCantha': 14,
                            'Lucky': 15,
                            'Unlucky': 16,
                            'Sunspear': 17,
                            'ElonaExploration': 18,
                            'ProtectorofElona': 19,
                            'Lightbringer': 20,
                            'Ldoa': 21,
                            'Gamer': 23,
                            'TyrianEliteSkillHunter': 24,
                            'TyrianVanquisher': 25,
                            'CanthanEliteSkillHunter': 26,
                            'CanthanVanquisher': 27,
                            'TyrianEliteSkillHunter2': 28,
                            'LegendaryGuardian': 31,
                            'LegendaryVanquisher': 33,
                            'SweetTooth': 34,
                            'GuardianofTyria': 35,
                            'Asura': 38,
                            'Deldrimor': 39,
                            'EbonVanguard': 40,
                            'Norn': 41,
                            'EotnMastery': 42,
                            'PartyAnimal': 43,
                            'Zaishen': 44,
                            'TreasureHunter': 45,
                            'Wisdom': 46,
                        }),
                    }),
                    'ScrollBar': 3,
                }),
            }),
            'TitlesTab': 4294967293,
            'FactionTab': 4294967294,
            'AccountTab': 4294967295,
        }),
        'CharacterName': 3,
        'Class': 4,
    }),
    'BackButton': 'Back',
    'Frame': 'Background',
    'MissionGoals': 'Blurb',
    'BodyScaleFrame': 'BodyScale',
    'Boots': 'Boots',
    'AcceptButton': 'BtnAccept',
    'MerchantBuyButton': 'BtnBuy',
    'CancelButton': 'BtnCancel',
    'CraftButton': 'BtnCraft',
    'CustomizeWeaponButton': 'BtnCustomize',
    'DeclineButton': 'BtnDecline',
    'EquipNow': 'BtnEquip',
    'CloseWindowButton': 'BtnExit',
    'MaxButton': 'BtnMax',
    'MinimizeWindowButton': 'BtnMin',
    'SubmitOfferButton': 'BtnModify',
    'DidNotCleaningDisconnectPopupCharselectNoButton': 'BtnNo',
    'OkButton': 'BtnOk',
    'RestoreWindowButton': 'BtnRestore',
    'ToggleChatButton': 'BtnStateSwitch',
    'TradeButton': ('BtnTrade', {
        'Button': 0,
    }),
    'ViewButton': 'BtnView',
    'DidNotCleaningDisconnectPopupCharselectYesButton': 'BtnYes',
    'DropBundleButton': 'Bundle',
    'MouseInstructionsFrame': 'CameraHelp',
    'Cape': 'Cape',
    'ItemsOffered': 'CartPartner',
    'OfferedItems': ('CartPlayer', {
        'C1': (1, {
            'Item1': 0,
            'Item2': 1,
            'Item3': 2,
            'Item4': 3,
            'Item5': 4,
            'Item6': 5,
            'Item7': 6,
        }),
    }),
    'SelectCampaignSliderFrame': ('Chapter', {
        'Child': 0,
    }),
    'CreateButton': 'CharCreate',
    'CreateButtonGreyedOut': 'CharCreateNoChar',
    'DeleteButton': 'CharDelete',
    'Chat': 'Chat',
    'WeaponSet1': 'CheckF1',
    'WeaponSet2': 'CheckF2',
    'WeaponSet3': 'CheckF3',
    'WeaponSet4': 'CheckF4',
    'Chest': 'ChestArmor',
    'ArmorDye': ('Colors', {
        'GreyDye': 0,
        'BlueDye': 1,
        'GreenDye': 2,
        'PurpleDye': 3,
        'RedDye': 4,
        'YellowDye': 5,
        'BrownDye': 6,
        'OrangeDye': 7,
    }),
    'Compass': 'Compass',
    'WeaponSetsButton': 'ConfigEquipSets',
    'Costume': 'Costume1',
    'CostumeHeadpiece': 'Costume2',
    'DamageMonitor': 'DamageMonitor',
    'SkillsAndAttributesWindow': 'DeckBuilder',
    'DistrictList': ('District', {
        'Dropdown': 0,
    }),
    'SkillCaptureDialog': ('DlgSkillCapture', {
        'Content': 0,
    }),
    'EquipSkillWindow': 'DlgSkillPlace',
    'TradeWindow': 'DlgTrade',
    'PerformanceMonitor': ('DnStat', {
        'Frame': 0,
    }),
    'CharacterPreviewFrame': 'Doll',
    'FrameSpacer': 'Download',
    'EditAccountButton': 'EditAcct',
    'TextArea': 'EditMessage',
    'WhisperReciever': 'EditName',
    'EffectsMonitor': 'Effects',
    'Option1': 'Face1',
    'Option10': 'Face10',
    'Option11': 'Face11',
    'Option12': 'Face12',
    'Option13': 'Face13',
    'Option14': 'Face14',
    'Option15': 'Face15',
    'Option16': 'Face16',
    'Option2': 'Face2',
    'Option3': 'Face3',
    'Option4': 'Face4',
    'Option5': 'Face5',
    'Option6': 'Face6',
    'Option7': 'Face7',
    'Option8': 'Face8',
    'Option9': 'Face9',
    'FaceFrame': 'FaceType',
    'FeetFrame': 'Feet',
    'FeetText': 'FeetLabel',
    'ChatChannelsToggle': ('Filters', {
        'Local': 0,
        'Guild': 1,
        'Team': 2,
        'Trade': 3,
        'Alliance': 4,
        'Emotes': 5,
    }),
    'FriendsWindow': 'Friends',
    'ScreenFrame': ('Game', {
        'CharacterCreateCharacterFrame': 3,
        'Child': (5, {
            'CharacterSelectFrame': (1, {
                'DeleteCharacterFrame': (15, {
                    'Text': 0,
                    'NameInput': 1,
                    'DeleteButton': 2,
                    'CancelButton': 3,
                }),
            }),
            'CharacterCreateCharacterTypeFrame': 2,
        }),
        'C6': (6, {
            'ScreenFrame': (1, {
                'SkipCutsceneButton': 0,
            }),
            'LesserSalvageWindow': (111, {
                'SalvageWithLesserKitCancel': 4,
                'SalvageWithLesserKitConfirm': 6,
            }),
            'ExpertSalvageUnidentifiedItem': (112, {
                'Cancel': 4,
                'Confirm': 6,
            }),
            'SalvageMaterialsDialog': (113, {
                'QuestionFrame': 0,
                'Label': 1,
                'NoButton': 4,
                'YesButton': 6,
            }),
            'LogOut': 117,
            'Options': 126,
            'NpcNameplateFrame': 50331649,
            'NpcNameplateFrame2': 50331650,
            'NpcNameplateFrame3': 50331651,
            'NpcNameplateFrame4': 50331652,
            'NpcNameplateFrame5': 50331653,
            'NpcNameplateFrame6': 50331654,
            'NpcNameplateFrame7': 50331655,
            'NpcNameplateFrame8': 50331656,
            'NpcNameplateFrame9': 50331657,
            'NpcNameplateFrame10': 50331658,
            'NpcNameplateFrame11': 50331659,
            'NpcNameplateFrame12': 50331660,
            'NpcNameplateFrame13': 50331661,
            'NpcNameplateFrame14': 50331662,
            'NpcNameplateFrame15': 50331663,
            'NpcNameplateFrame16': 50331665,
            'NpcNameplateFrame17': 50331666,
            'NpcNameplateFrame18': 50331667,
            'NpcNameplateFrame19': 50331668,
            'NpcNameplateFrame20': 50331669,
            'NpcNameplateFrame21': 50331670,
            'NpcNameplateFrame22': 50331671,
            'NpcNameplateFrame23': 50331672,
            'NpcNameplateFrame24': (50331673, {
                'NpcNameplateFrame': 0,
            }),
            'NpcNameplateFrame25': (50331674, {
                'NpcNameplateFrame': 0,
            }),
            'NpcNameplateFrame26': (50331675, {
                'NpcNameplateFrame': 0,
            }),
            'NpcNameplateFrame27': 50331676,
            'NpcNameplateFrame28': 50331677,
            'NpcNameplateFrame29': 50331678,
            'NpcNameplateFrame30': 50331679,
            'NpcNameplateFrame31': 50331680,
            'NpcNameplateFrame32': 50331681,
            'NpcNameplateFrame33': (50331682, {
                'NpcNameplateFrame': 0,
            }),
            'NpcNameplateFrame34': 50331683,
            'NpcNameplateFrame35': 50331684,
            'NpcNameplateFrame36': 50331685,
            'NpcNameplateFrame37': 50331688,
            'NpcNameplateFrame38': 50331689,
            'NpcNameplateFrame39': 50331690,
            'NpcNameplateFrame40': 50331691,
            'NpcNameplateFrame41': 50331692,
            'NpcNameplateFrame42': 50331693,
            'NpcNameplateFrame43': 50331694,
            'NpcNameplateFrame44': 50331695,
            'NpcNameplateFrame45': 50331696,
            'NpcNameplateFrame46': 50331697,
            'NpcNameplateFrame47': 50331698,
            'NpcNameplateFrame48': 50331699,
            'NpcNameplateFrame49': 50331700,
            'NpcNameplateFrame50': 50331701,
            'NpcNameplateFrame51': 50331702,
            'NpcNameplateFrame52': 50331703,
            'NpcNameplateFrame53': 50331704,
            'NpcNameplateFrame54': 50331705,
            'NpcNameplateFrame55': 50331706,
            'NpcNameplateFrame56': 50331707,
            'NpcNameplateFrame57': 50331708,
            'NpcNameplateFrame58': 50331709,
            'NpcNameplateFrame59': 50331710,
            'NpcNameplateFrame60': 50331711,
            'NpcNameplateFrame61': 50331785,
            'NpcNameplateFrame62': 50331786,
            'NpcNameplateFrame63': 50331787,
            'NpcNameplateFrame64': 50331788,
            'NpcNameplateFrame65': 50331789,
            'NpcNameplateFrame66': 50331790,
            'NpcNameplateFrame67': 50331791,
            'NpcNameplateFrame68': 50331792,
            'NpcNameplateFrame69': 50331793,
            'NpcNameplateFrame70': 50331794,
            'NpcNameplateFrame71': 50331795,
            'NpcNameplateFrame72': 50331796,
            'NpcNameplateFrame73': 50331797,
            'NpcNameplateFrame74': 50331798,
            'NpcNameplateFrame75': 50331799,
            'NpcNameplateFrame76': 50331800,
            'NpcNameplateFrame77': 50331801,
            'NpcNameplateFrame78': 50331802,
            'NpcNameplateFrame79': 50331803,
            'NpcNameplateFrame80': 50331804,
            'NpcNameplateFrame81': 50331819,
            'NpcNameplateFrame82': 50331820,
            'NpcNameplateFrame83': 50331821,
            'NpcNameplateFrame84': 50331822,
            'NpcNameplateFrame85': 50331823,
            'NpcNameplateFrame86': 50331825,
            'NpcNameplateFrame87': 50331828,
            'NpcNameplateFrame88': 50331829,
            'NpcNameplateFrame89': 50331832,
        }),
        'DidNotCleaningDisconnectPopupCharselect': 10,
        'LeaveYourPartyDialog': (12, {
            'NoLeaveYourPartyButton': 4,
            'YesLeaveYourPartyButton': 6,
        }),
        'C17': (17, {
            'GuildWarsWasUnableToCompleteTheOperationPopupCharselect': (0, {
                'ExclimationMark': 0,
                'TextFrame': 1,
                'OkButton': 5,
            }),
        }),
    }),
    'Gloves': 'Gloves',
    'GoldInfo': ('Gold', {
        'Gold': 0,
        'Platinum': 1,
        'Qty': 2,
        'PlatinumQty': 3,
    }),
    'GoldOffer': 'GoldEditPlayer',
    'GoldOffered': 'GoldPartner',
    'GuildWindow': 'Guild',
    'HairColorFrame': 'HairColor',
    'HairStyleFrame': 'HairStyle',
    'HandsFrame': 'Hands',
    'HandsText': 'HandsLabel',
    'HeadFrame': 'Head',
    'HeadText': 'HeadLabel',
    'Head': 'Helm',
    'HelpWindow': 'HelpGuide',
    'HideUiCheckbox': 'HideUi',
    'Hints': 'Hint',
    'IdentifyAll': 'IdentifyAll',
    'Icons': 'ImgHelp',
    'DidNotCleaningDisconnectPopupCharselectQuestionMark': 'ImgIcon',
    'XunlaiWindow': ('InvAccount', {
        'StorageFrame': (0, {
            'Content': (0, {
                'Item1': 2,
                'Item2': 3,
                'Item3': 4,
                'Item4': 5,
                'Item5': 6,
                'Item6': 7,
                'Item7': 8,
                'Item8': 9,
                'Item9': 10,
                'Item10': 11,
                'Item11': 12,
                'Item12': 13,
                'Item13': 14,
                'Item14': 15,
                'Item15': 16,
                'Item16': 17,
                'Item17': 18,
                'Item18': 19,
                'Item19': 20,
                'Item20': 21,
                'Item21': 22,
                'Item22': 23,
                'Item23': 24,
                'Item24': 25,
                'Item25': 26,
            }),
            'Content2': (1, {
                'Item1': 2,
                'Item2': 3,
                'Item3': 4,
                'Item4': 5,
                'Item5': 6,
                'Item6': 7,
                'Item7': 8,
                'Item8': 9,
                'Item9': 10,
                'Item10': 11,
                'Item11': 12,
                'Item12': 13,
                'Item13': 14,
                'Item14': 15,
                'Item15': 16,
                'Item16': 17,
                'Item17': 18,
                'Item18': 19,
                'Item19': 20,
                'Item20': 21,
                'Item21': 22,
                'Item22': 23,
                'Item23': 24,
                'Item24': 25,
                'Item25': 26,
            }),
            'Content3': (2, {
                'Item1': 2,
                'Item2': 3,
                'Item3': 4,
                'Item4': 5,
                'Item5': 6,
                'Item6': 7,
                'Item7': 8,
                'Item8': 9,
                'Item9': 10,
                'Item10': 11,
                'Item11': 12,
                'Item12': 13,
                'Item13': 14,
                'Item14': 15,
                'Item15': 16,
                'Item16': 17,
                'Item17': 18,
                'Item18': 19,
                'Item19': 20,
                'Item20': 21,
                'Item21': 22,
                'Item22': 23,
                'Item23': 24,
                'Item24': 25,
                'Item25': 26,
            }),
            'Content4': (3, {
                'Item1': 2,
                'Item2': 3,
                'Item3': 4,
                'Item4': 5,
                'Item5': 6,
                'Item6': 7,
                'Item7': 8,
                'Item8': 9,
                'Item9': 10,
                'Item10': 11,
                'Item11': 12,
                'Item12': 13,
                'Item13': 14,
                'Item14': 15,
                'Item15': 16,
                'Item16': 17,
                'Item17': 18,
                'Item18': 19,
                'Item19': 20,
                'Item20': 21,
                'Item21': 22,
                'Item22': 23,
                'Item23': 24,
                'Item24': 25,
                'Item25': 26,
            }),
            'Content5': (4, {
                'Item1': 2,
                'Item2': 3,
                'Item3': 4,
                'Item4': 5,
                'Item5': 6,
                'Item6': 7,
                'Item7': 8,
                'Item8': 9,
                'Item9': 10,
                'Item10': 11,
                'Item11': 12,
                'Item12': 13,
                'Item13': 14,
                'Item14': 15,
                'Item15': 16,
                'Item16': 17,
                'Item17': 18,
                'Item18': 19,
                'Item19': 20,
                'Item20': 21,
                'Item21': 22,
                'Item22': 23,
                'Item23': 24,
                'Item24': 25,
                'Item25': 26,
            }),
            'Content6': (5, {
                'Item1': 2,
                'Item2': 3,
                'Item3': 4,
                'Item4': 5,
                'Item5': 6,
                'Item6': 7,
                'Item7': 8,
                'Item8': 9,
                'Item9': 10,
                'Item10': 11,
                'Item11': 12,
                'Item12': 13,
                'Item13': 14,
                'Item14': 15,
                'Item15': 16,
                'Item16': 17,
                'Item17': 18,
                'Item18': 19,
                'Item19': 20,
                'Item20': 21,
                'Item21': 22,
                'Item22': 23,
                'Item23': 24,
                'Item24': 25,
                'Item25': 26,
            }),
            'Content7': (6, {
                'Item1': 2,
                'Item2': 3,
                'Item3': 4,
                'Item4': 5,
                'Item5': 6,
                'Item6': 7,
                'Item7': 8,
                'Item8': 9,
                'Item9': 10,
                'Item10': 11,
                'Item11': 12,
                'Item12': 13,
                'Item13': 14,
                'Item14': 15,
                'Item15': 16,
                'Item16': 17,
                'Item17': 18,
                'Item18': 19,
                'Item19': 20,
                'Item20': 21,
                'Item21': 22,
                'Item22': 23,
                'Item23': 24,
                'Item24': 25,
                'Item25': 26,
            }),
            'Content8': (7, {
                'Item1': 2,
                'Item2': 3,
                'Item3': 4,
                'Item4': 5,
                'Item5': 6,
                'Item6': 7,
                'Item7': 8,
                'Item8': 9,
                'Item9': 10,
                'Item10': 11,
                'Item11': 12,
                'Item12': 13,
                'Item13': 14,
                'Item14': 15,
                'Item15': 16,
                'Item16': 17,
                'Item17': 18,
                'Item18': 19,
                'Item19': 20,
                'Item20': 21,
                'Item21': 22,
                'Item22': 23,
                'Item23': 24,
                'Item24': 25,
                'Item25': 26,
            }),
            'Content9': (8, {
                'Item1': 2,
                'Item2': 3,
                'Item3': 4,
                'Item4': 5,
                'Item5': 6,
                'Item6': 7,
                'Item7': 8,
                'Item8': 9,
                'Item9': 10,
                'Item10': 11,
                'Item11': 12,
                'Item12': 13,
                'Item13': 14,
                'Item14': 15,
                'Item15': 16,
                'Item16': 17,
                'Item17': 18,
                'Item18': 19,
                'Item19': 20,
                'Item20': 21,
                'Item21': 22,
                'Item22': 23,
                'Item23': 24,
                'Item24': 25,
                'Item25': 26,
            }),
            'Content10': (9, {
                'Item1': 2,
                'Item2': 3,
                'Item3': 4,
                'Item4': 5,
                'Item5': 6,
                'Item6': 7,
                'Item7': 8,
                'Item8': 9,
                'Item9': 10,
                'Item10': 11,
                'Item11': 12,
                'Item12': 13,
                'Item13': 14,
                'Item14': 15,
                'Item15': 16,
                'Item16': 17,
                'Item17': 18,
                'Item18': 19,
                'Item19': 20,
                'Item20': 21,
                'Item21': 22,
                'Item22': 23,
                'Item23': 24,
                'Item24': 25,
                'Item25': 26,
            }),
            'Content11': (10, {
                'Item1': 2,
                'Item2': 3,
                'Item3': 4,
                'Item4': 5,
                'Item5': 6,
                'Item6': 7,
                'Item7': 8,
                'Item8': 9,
                'Item9': 10,
                'Item10': 11,
                'Item11': 12,
                'Item12': 13,
                'Item13': 14,
                'Item14': 15,
                'Item15': 16,
                'Item16': 17,
                'Item17': 18,
                'Item18': 19,
                'Item19': 20,
                'Item20': 21,
                'Item21': 22,
                'Item22': 23,
                'Item23': 24,
                'Item24': 25,
                'Item25': 26,
            }),
            'Content12': (11, {
                'Item1': 2,
                'Item2': 3,
                'Item3': 4,
                'Item4': 5,
                'Item5': 6,
                'Item6': 7,
                'Item7': 8,
                'Item8': 9,
                'Item9': 10,
                'Item10': 11,
                'Item11': 12,
                'Item12': 13,
                'Item13': 14,
                'Item14': 15,
                'Item15': 16,
                'Item16': 17,
                'Item17': 18,
                'Item18': 19,
                'Item19': 20,
                'Item20': 21,
                'Item21': 22,
                'Item22': 23,
                'Item23': 24,
                'Item24': 25,
                'Item25': 26,
            }),
            'Content13': (12, {
                'Item1': 2,
                'Item2': 3,
                'Item3': 4,
                'Item4': 5,
                'Item5': 6,
                'Item6': 7,
                'Item7': 8,
                'Item8': 9,
                'Item9': 10,
                'Item10': 11,
                'Item11': 12,
                'Item12': 13,
                'Item13': 14,
                'Item14': 15,
                'Item15': 16,
                'Item16': 17,
                'Item17': 18,
                'Item18': 19,
                'Item19': 20,
                'Item20': 21,
                'Item21': 22,
                'Item22': 23,
                'Item23': 24,
                'Item24': 25,
                'Item25': 26,
            }),
            'Content14': (13, {
                'Item1': 2,
                'Item2': 3,
                'Item3': 4,
                'Item4': 5,
                'Item5': 6,
                'Item6': 7,
                'Item7': 8,
                'Item8': 9,
                'Item9': 10,
                'Item10': 11,
                'Item11': 12,
                'Item12': 13,
                'Item13': 14,
                'Item14': 15,
                'Item15': 16,
                'Item16': 17,
                'Item17': 18,
                'Item18': 19,
                'Item19': 20,
                'Item20': 21,
                'Item21': 22,
                'Item22': 23,
                'Item23': 24,
                'Item24': 25,
                'Item25': 26,
            }),
            'Content15': (14, {
                'Iron': 1,
                'Cloth': 2,
                'TannedHide': 3,
                'Wood': 4,
                'Dust': 5,
                'Scale': 6,
                'Chitin': 7,
                'Bones': 8,
                'Granite': 9,
                'PlantFibers': 10,
                'Feather': 11,
                'Fur': 12,
                'Linen': 13,
                'Damask': 14,
                'Silk': 15,
                'Ectoplasm': 16,
                'Steel': 17,
                'DeldrimorSteel': 18,
                'MonstrousClaws': 19,
                'MonstrousEye': 20,
                'MonstrousFang': 21,
                'Diamond': 22,
                'Ruby': 23,
                'Sapphire': 24,
                'ObsidianShard': 25,
                'Amber': 26,
                'Jadeite': 27,
                'Charcoal': 28,
                'GlassVial': 29,
                'Leather': 30,
                'ElonianLeather': 31,
                'Ink': 32,
                'Parchment': 33,
                'Vellum': 34,
                'Spiritwood': 35,
                'Onyx': 36,
            }),
            'TabMaterialStorage': 4294967281,
            'Tab14As': 4294967282,
            'Tab13': 4294967283,
            'Tab12': 4294967284,
            'Tab11': 4294967285,
            'Tab10': 4294967286,
            'Tab9': 4294967287,
            'Tab8': 4294967288,
            'Tab7': 4294967289,
            'Tab6': 4294967290,
            'Tab5': 4294967291,
            'Tab4': 4294967292,
            'Tab3': 4294967293,
            'Tab2': 4294967294,
            'Tab1': 4294967295,
        }),
        'GoldFrame': 1,
        'GoldFrame2': (2, {
            'GoldIcon': 0,
            'PlatinumIcon': 1,
            'GoldValue': 2,
            'PlatinumValue': 3,
        }),
        'DepositFundsButton': 3,
        'WithdrawFundsButton': 4,
        'DepositAllMaterials': 5,
    }),
    'InventoryBagsWindow': ('InvAggregate', {
        'Content': (0, {
            'C0': (0, {
                'C0': (0, {
                    'Bag1': (0, {
                        'Slot1': 2,
                        'Slot2': 3,
                        'Slot3': 4,
                        'Slot4': 5,
                        'Slot5': 6,
                        'Slot6': 7,
                        'Slot7': 8,
                        'Slot8': 9,
                        'Slot9': 10,
                        'Slot10': 11,
                        'Slot11': 12,
                        'Slot12': 13,
                        'Slot13': 14,
                        'Slot14': 15,
                        'Slot15': 16,
                        'Slot16': 17,
                        'Slot17': 18,
                        'Slot18': 19,
                        'Slot19': 20,
                        'Slot20': 21,
                    }),
                    'C1': (1, {
                        'Slot1': 2,
                        'Slot2': 3,
                        'Slot3': 4,
                        'Slot4': 5,
                        'Slot5': 6,
                    }),
                    'C2': (2, {
                        'Slot1': 2,
                        'Slot2': 3,
                        'Slot3': 4,
                        'Slot4': 5,
                        'Slot5': 6,
                        'Slot6': 7,
                        'Slot7': 8,
                        'Slot8': 9,
                        'Slot9': 10,
                        'Slot10': 11,
                    }),
                    'C3': (3, {
                        'Slot1': 2,
                        'Slot2': 3,
                        'Slot3': 4,
                        'Slot4': 5,
                        'Slot5': 6,
                        'Slot6': 7,
                        'Slot7': 8,
                        'Slot8': 9,
                        'Slot9': 10,
                        'Slot10': 11,
                    }),
                }),
            }),
        }),
    }),
    'EnableWeaponSetsWindow': 'InvEquipSet',
    'UpgradeWindow': ('InvUpgrade', {
        'Cancel': 0,
        'Confirm': 1,
    }),
    'InventoryWindow': ('Inventory', {
        'Backpack': (0, {
            'Slot1': 2,
            'Slot2': 3,
        }),
        'BeltPouch': (1, {
            'Slot1': 2,
            'Slot2': 3,
            'Slot10': 11,
        }),
        'Bag1': (2, {
            'Slot1': 2,
            'Slot2': 3,
        }),
        'Bag2': (3, {
            'Slot1': 2,
            'Slot2': 3,
        }),
        'EquipmentPack': (4, {
            'Slot1': 2,
            'Slot2': 3,
            'Slot15': 16,
            'Slot20': 21,
        }),
        'BagsBar': 6,
        'CharacterInfo': 7,
        'DividerBelowHeroes': 8,
        'PartyPortraits': (9, {
            'Portrait1': 16777230,
            'Portrait2': 16777231,
            'Portrait3': 16777232,
            'Portrait4': 16777233,
            'Portrait5': 16777234,
            'Portrait6': 16777235,
            'Portrait7': 16777236,
            'Portrait8': 16777237,
            'Player2': 16777254,
            'Player1': 16777269,
            'Player3': 16777271,
            'Player4': 16777272,
            'Player5': 16777273,
            'Player6': 16777274,
            'Player7': 16777275,
            'Player8': 16777276,
        }),
    }),
    'ArmorFrame': 'ItemColor',
    'ArmorIcon': 'ItemIcon',
    'Text': 'Label',
    'Pants': 'LegArmor',
    'LegsFrame': 'Legs',
    'LegsText': 'LegsLabel',
    'ExperienceBar': ('LevelProgress', {
        'Frame': 1,
    }),
    'SkillTrainerWindow': ('ListStock', {
        'DisplayModeButton': 3,
    }),
    'ChatLog': ('Log', {
        'Frame': (0, {
            'Text': (0, {
                'Area': (0, {
                    'Line1': (0, {
                        'Text': (0, {
                            'Sender': 2,
                        }),
                    }),
                }),
            }),
            'Scrollbar': 3,
        }),
    }),
    'LogOutButton': 'Logout',
    'MissionMap': 'MapWindow',
    'MissionProgress': 'MissionProgress',
    'MissionStatusAndScoreDisplay': ('MissionStatus', {
        'C0': (0, {
            'C1': (1, {
                'CancelEnterMissionButton': 1,
            }),
        }),
    }),
    'NpcDialog': ('NPCInteract', {
        'UseLockpickButton': 1,
        'C2': (2, {
            'C0': (0, {
                'C0': (0, {
                    'Option': (1, {
                        'Icon': 1,
                        'Icon2': 2,
                    }),
                }),
            }),
            'ScrollBar': 3,
        }),
    }),
    'CharacerNameFrame': ('Name', {
        'TitleText': 0,
        'Child': (1, {
            'CharacterNameInput': 1,
            'MiddleText': 2,
            'UnderInputText': 4,
            'CharacterNameCheck1': 5,
            'CharacterNameCheck2': 6,
            'CharacterNameCheck4': 7,
            'CharacterNameCheck3': 9,
        }),
    }),
    'NextButton': 'Next',
    'Notifications': 'NotifyText',
    'Dialogue1': 'NpcDialogue1',
    'Dialogue2': 'NpcDialogue2',
    'ObserveWindow': 'ObserveSelect',
    'OptionsWindow': ('Options', {
        'GwVersion': 0,
        'InnerFrame': (1, {
            'GeneralOptionsTabInternal': 0,
            'GraphicsOptionsTabInternal': 1,
            'SoundOptionsTabInternal': 2,
            'ControlOptionsTabInternal': 3,
            'InterfaceOptionsTabInternal': 4,
            'GamepadOptionsTab': 4294967290,
            'InterfaceOptionsTab': 4294967291,
            'ControlOptionsTab': 4294967292,
            'SoundOptionsTab': 4294967293,
            'GraphicsOptionsTab': 4294967294,
            'GeneralOptionsTab': 4294967295,
        }),
    }),
    'OptionsButton': 'OptionsBtn',
    'PartyFormation': ('Party', {
        'Explorable': (0, {
            'C0': (0, {
                'C0': (0, {
                    'MembersParentExplorable': 0,
                    'PetsHeader': (8, {
                        'Expand': 0,
                        'Title': 1,
                    }),
                }),
            }),
        }),
        'Outpost': (1, {
            'ButtonKick': 1,
            'ButtonLeave': 2,
            'ButtonSearch': 4,
            'GameMode': (7, {
                'HardMode': 0,
                'NormalMode': 1,
                'Text': 2,
            }),
            'Members': (8, {
                'Frame': (0, {
                    'C0': (0, {
                        'C0': (0, {
                            'Parent': (0, {
                                'C1': (1, {
                                    'ReadyToggle': 1,
                                }),
                                'Member7': 7,
                                'C10': (10, {
                                    'Player1': 0,
                                    'ReadyFlag': 1,
                                    'Player8': (94, {
                                        'HeroWindowToggle': 1,
                                    }),
                                    'Player7': (104, {
                                        'HeroWindowToggle': 1,
                                    }),
                                    'Player4': (110, {
                                        'HeroWindowToggle': 1,
                                    }),
                                    'Player6': (116, {
                                        'HeroWindowToggle': 1,
                                    }),
                                    'Player5': (121, {
                                        'HeroWindowToggle': 1,
                                    }),
                                    'Player3': (142, {
                                        'HeroWindowToggle': 1,
                                    }),
                                    'Player2': (145, {
                                        'Frame': (0, {
                                            'PlayerName': 2,
                                        }),
                                        'HeroWindowToggle': 1,
                                    }),
                                }),
                            }),
                        }),
                    }),
                }),
            }),
        }),
    }),
    'GuildBattleWindow': 'PartyBattle',
    'PartySearchWindow': ('PartySearch', {
        'Panel': (14, {
            'SlotPrev2': 4294967293,
            'SlotPrev': 4294967294,
            'SlotLast': 4294967295,
        }),
    }),
    'PetControl': 'PetCommanderPlayer',
    'PlayButton': 'Play',
    'PlayButtonGreyedOut': 'PlayNoChar',
    'Weapon': 'PrimaryHand',
    'CharacterCreateCharacterProfessionFrame': ('Profession', {
        'Child': 0,
        'BottomText': 1,
    }),
    'MercenarySlotAd': ('Purchase', {
        'EnterStoreButton': 0,
        'SmallText': 1,
        'LargeText': 2,
    }),
    'QuestLogWindow': ('Quest', {
        'C3': (3, {
            'ScrollBar': 3,
        }),
    }),
    'Root': ('Root', {
        'C2': (2, {
            'C6': (6, {
                'C100': (100, {
                    'C2': (2, {
                        'ConfirmEnterMissionButton': 6,
                    }),
                }),
            }),
        }),
    }),
    'SalvageWindow': ('Salvage', {
        'OptionsWindowConfirmMaterialsWindow': (0, {
            'Cancel': 4,
            'Confirm': 6,
        }),
        'CancelButton': 1,
        'Button': 2,
        'Details': 3,
        'HeaderLabel': 4,
        'Options': (5, {
            'Option1': 0,
            'Option2': 1,
            'Option3': 2,
            'Option4': 3,
        }),
    }),
    'Arrow': 'ScaleSlider',
    'Offhand': 'SecondaryHand',
    'SelectedOption': 'Selection',
    'CharacterFrame': ('Selector', {
        'Child': 0,
    }),
    'CharacterCreateCharacterSexFrame': ('Sex', {
        'Child': 0,
    }),
    'ShowCheckbox': 'ShowHead',
    'Skillbar': ('SkillBar', {
        'Skill1': (0, {
            'Frame': (2, {
                'Number': 6,
                'Frame': 13,
            }),
        }),
        'Skill2': (1, {
            'Frame': (2, {
                'Number': 6,
            }),
        }),
        'Skill3': (2, {
            'Frame': (2, {
                'Number': 6,
            }),
        }),
        'Skill4': (3, {
            'Frame': (2, {
                'Number': 6,
                'Frame': 13,
            }),
        }),
        'Skill5': (4, {
            'Frame': (2, {
                'Number': 6,
            }),
        }),
        'Skill6': (5, {
            'Frame': (2, {
                'Number': 6,
                'Frame': 13,
            }),
        }),
        'Skill7': (6, {
            'Frame': (2, {
                'Number': 6,
            }),
        }),
        'Skill8': (7, {
            'Frame': (2, {
                'Number': 6,
            }),
        }),
    }),
    'SkillMonitor': 'SkillMonitor',
    'SkillTome': 'SkillTome',
    'UpkeepMonitor': 'SkillUpkeep',
    'SkillWarmup': 'SkillWarmup',
    'SkinColorFrame': 'SkinColor',
    'Ruler': 'SliderMarker',
    'Set1': 'Slot1',
    'Set2': 'Slot2',
    'Set3': 'Slot3',
    'Set4': 'Slot4',
    'EquipmentPackSlot': 'Slot5',
    'CharacterSlotsInUseFrame': 'SlotCount',
    'SortFrame': ('Sort', {
        'Dropdown': (0, {
            'DropdownWindow': 0,
        }),
        'Text': 1,
    }),
    'InGameClock': 'StClock',
    'MenuButton': ('StartMenuBar', {
        'Menu': (0, {
            'HeroMenu': 1,
            'Seperator': 1608675812,
        }),
    }),
    'EnergyBar': ('StatEnergy', {
        'Frame': 4,
    }),
    'HealthBar': ('StatHealth', {
        'Frame': 3,
    }),
    'CreateCharacterBottomFrame': ('State', {
        'CampaignTab': (0, {
            'Text': 1,
        }),
        'ProfessionTab': (1, {
            'Text': 1,
        }),
        'SexTab': (2, {
            'Text': 1,
        }),
        'AppearanceTab': (3, {
            'Text': 1,
        }),
        'BodyTab': (4, {
            'Text': 1,
        }),
        'NameTab': (5, {
            'Text': 1,
        }),
    }),
    'BackButton2': 'StateCancel',
    'CreateButton2': 'StateCreate',
    'NextButton2': 'StateNext',
    'BackButton3': 'StatePrev',
    'TopText': 'StateTitle',
    'StatusDropdown': 'StatusOverride',
    'ChatChannels': ('Tabs', {
        'AllText': 0,
        'AlianceText': 1,
        'GuildText': 2,
        'TeamText': 3,
        'TradeText': 4,
        'WhisperText': 5,
        'Whisper': 4294967290,
        'Trade': 4294967291,
        'Team': 4294967292,
        'Guild': 4294967293,
        'Alliance': 4294967294,
        'All': 4294967295,
    }),
    'TargetDisplay': 'Target',
    'Label': 'Text',
    'ChooseYourCharacterTypeText': 'Title',
    'ChestFrame': 'Torso',
    'ChestText': 'TorsoLabel',
    'DestroyItemSlot': 'Trash',
    'GoldText': 'TxtGold',
    'Text2': 'TxtHelp',
    'DidNotCleaningDisconnectPopupCharselectTextFrame': 'TxtMessage',
    'OfferedItems2': 'TxtPartnerModifying',
    'TradePartner': 'TxtPartnerOffer',
    'YourOfferLabel': 'TxtPlayerOffer',
    'Caption': 'TxtPrompt',
    'Merchant': ('Vendor', {
        'C0': (0, {
            'C0': (0, {
                'BuyButton': 0,
                'CloseButton': 1,
                'TraderCloseButton': 2,
                'C4': (4, {
                    'C0': (0, {
                        'ItemContainer': (0, {
                            'Item1': 489,
                            'Item2': 490,
                        }),
                    }),
                }),
                'Exchange': 6,
                'Goodbye': 7,
                'RequestQuoteButton': 14,
            }),
            'C1': (1, {
                'CustomizeButton': 1,
            }),
            'QuoteField': 4294967294,
        }),
    }),
    'ToggleCape': 'VisCape',
    'ToggleCostume': 'VisCostume1',
    'ToggleCostumeHeadpiece': 'VisCostume2',
    'ToggleHeadpiece': 'VisHelm',
    'WeaponBar': 'WeaponBar',
    'CharacterInfoFrame': ('info', {
        'Text': 0,
        'Text2': 1,
        'Text3': 2,
        'Text4': 3,
        'Text5': 4,
        'Text6': 6,
    }),
}

# Keys whose code tail contains per-session runtime codes (>= 0x03000000).
DYNAMIC_KEYS: set = {
    'ChatChannels.All',
    'ChatChannels.Alliance',
    'ChatChannels.Guild',
    'ChatChannels.Team',
    'ChatChannels.Trade',
    'ChatChannels.Whisper',
    'HeroWindow.Tabs.AccountTab',
    'HeroWindow.Tabs.FactionTab',
    'HeroWindow.Tabs.TitlesTab',
    'MenuButton.Menu.Seperator',
    'Merchant.C0.QuoteField',
    'OptionsWindow.InnerFrame.ControlOptionsTab',
    'OptionsWindow.InnerFrame.GamepadOptionsTab',
    'OptionsWindow.InnerFrame.GeneralOptionsTab',
    'OptionsWindow.InnerFrame.GraphicsOptionsTab',
    'OptionsWindow.InnerFrame.InterfaceOptionsTab',
    'OptionsWindow.InnerFrame.SoundOptionsTab',
    'PartySearchWindow.Panel.SlotLast',
    'PartySearchWindow.Panel.SlotPrev',
    'PartySearchWindow.Panel.SlotPrev2',
    'ScreenFrame.C6.NpcNameplateFrame',
    'ScreenFrame.C6.NpcNameplateFrame10',
    'ScreenFrame.C6.NpcNameplateFrame11',
    'ScreenFrame.C6.NpcNameplateFrame12',
    'ScreenFrame.C6.NpcNameplateFrame13',
    'ScreenFrame.C6.NpcNameplateFrame14',
    'ScreenFrame.C6.NpcNameplateFrame15',
    'ScreenFrame.C6.NpcNameplateFrame16',
    'ScreenFrame.C6.NpcNameplateFrame17',
    'ScreenFrame.C6.NpcNameplateFrame18',
    'ScreenFrame.C6.NpcNameplateFrame19',
    'ScreenFrame.C6.NpcNameplateFrame2',
    'ScreenFrame.C6.NpcNameplateFrame20',
    'ScreenFrame.C6.NpcNameplateFrame21',
    'ScreenFrame.C6.NpcNameplateFrame22',
    'ScreenFrame.C6.NpcNameplateFrame23',
    'ScreenFrame.C6.NpcNameplateFrame24',
    'ScreenFrame.C6.NpcNameplateFrame24.NpcNameplateFrame',
    'ScreenFrame.C6.NpcNameplateFrame25',
    'ScreenFrame.C6.NpcNameplateFrame25.NpcNameplateFrame',
    'ScreenFrame.C6.NpcNameplateFrame26',
    'ScreenFrame.C6.NpcNameplateFrame26.NpcNameplateFrame',
    'ScreenFrame.C6.NpcNameplateFrame27',
    'ScreenFrame.C6.NpcNameplateFrame28',
    'ScreenFrame.C6.NpcNameplateFrame29',
    'ScreenFrame.C6.NpcNameplateFrame3',
    'ScreenFrame.C6.NpcNameplateFrame30',
    'ScreenFrame.C6.NpcNameplateFrame31',
    'ScreenFrame.C6.NpcNameplateFrame32',
    'ScreenFrame.C6.NpcNameplateFrame33',
    'ScreenFrame.C6.NpcNameplateFrame33.NpcNameplateFrame',
    'ScreenFrame.C6.NpcNameplateFrame34',
    'ScreenFrame.C6.NpcNameplateFrame35',
    'ScreenFrame.C6.NpcNameplateFrame36',
    'ScreenFrame.C6.NpcNameplateFrame37',
    'ScreenFrame.C6.NpcNameplateFrame38',
    'ScreenFrame.C6.NpcNameplateFrame39',
    'ScreenFrame.C6.NpcNameplateFrame4',
    'ScreenFrame.C6.NpcNameplateFrame40',
    'ScreenFrame.C6.NpcNameplateFrame41',
    'ScreenFrame.C6.NpcNameplateFrame42',
    'ScreenFrame.C6.NpcNameplateFrame43',
    'ScreenFrame.C6.NpcNameplateFrame44',
    'ScreenFrame.C6.NpcNameplateFrame45',
    'ScreenFrame.C6.NpcNameplateFrame46',
    'ScreenFrame.C6.NpcNameplateFrame47',
    'ScreenFrame.C6.NpcNameplateFrame48',
    'ScreenFrame.C6.NpcNameplateFrame49',
    'ScreenFrame.C6.NpcNameplateFrame5',
    'ScreenFrame.C6.NpcNameplateFrame50',
    'ScreenFrame.C6.NpcNameplateFrame51',
    'ScreenFrame.C6.NpcNameplateFrame52',
    'ScreenFrame.C6.NpcNameplateFrame53',
    'ScreenFrame.C6.NpcNameplateFrame54',
    'ScreenFrame.C6.NpcNameplateFrame55',
    'ScreenFrame.C6.NpcNameplateFrame56',
    'ScreenFrame.C6.NpcNameplateFrame57',
    'ScreenFrame.C6.NpcNameplateFrame58',
    'ScreenFrame.C6.NpcNameplateFrame59',
    'ScreenFrame.C6.NpcNameplateFrame6',
    'ScreenFrame.C6.NpcNameplateFrame60',
    'ScreenFrame.C6.NpcNameplateFrame61',
    'ScreenFrame.C6.NpcNameplateFrame62',
    'ScreenFrame.C6.NpcNameplateFrame63',
    'ScreenFrame.C6.NpcNameplateFrame64',
    'ScreenFrame.C6.NpcNameplateFrame65',
    'ScreenFrame.C6.NpcNameplateFrame66',
    'ScreenFrame.C6.NpcNameplateFrame67',
    'ScreenFrame.C6.NpcNameplateFrame68',
    'ScreenFrame.C6.NpcNameplateFrame69',
    'ScreenFrame.C6.NpcNameplateFrame7',
    'ScreenFrame.C6.NpcNameplateFrame70',
    'ScreenFrame.C6.NpcNameplateFrame71',
    'ScreenFrame.C6.NpcNameplateFrame72',
    'ScreenFrame.C6.NpcNameplateFrame73',
    'ScreenFrame.C6.NpcNameplateFrame74',
    'ScreenFrame.C6.NpcNameplateFrame75',
    'ScreenFrame.C6.NpcNameplateFrame76',
    'ScreenFrame.C6.NpcNameplateFrame77',
    'ScreenFrame.C6.NpcNameplateFrame78',
    'ScreenFrame.C6.NpcNameplateFrame79',
    'ScreenFrame.C6.NpcNameplateFrame8',
    'ScreenFrame.C6.NpcNameplateFrame80',
    'ScreenFrame.C6.NpcNameplateFrame81',
    'ScreenFrame.C6.NpcNameplateFrame82',
    'ScreenFrame.C6.NpcNameplateFrame83',
    'ScreenFrame.C6.NpcNameplateFrame84',
    'ScreenFrame.C6.NpcNameplateFrame85',
    'ScreenFrame.C6.NpcNameplateFrame86',
    'ScreenFrame.C6.NpcNameplateFrame87',
    'ScreenFrame.C6.NpcNameplateFrame88',
    'ScreenFrame.C6.NpcNameplateFrame89',
    'ScreenFrame.C6.NpcNameplateFrame9',
    'XunlaiWindow.StorageFrame.Tab1',
    'XunlaiWindow.StorageFrame.Tab10',
    'XunlaiWindow.StorageFrame.Tab11',
    'XunlaiWindow.StorageFrame.Tab12',
    'XunlaiWindow.StorageFrame.Tab13',
    'XunlaiWindow.StorageFrame.Tab14As',
    'XunlaiWindow.StorageFrame.Tab2',
    'XunlaiWindow.StorageFrame.Tab3',
    'XunlaiWindow.StorageFrame.Tab4',
    'XunlaiWindow.StorageFrame.Tab5',
    'XunlaiWindow.StorageFrame.Tab6',
    'XunlaiWindow.StorageFrame.Tab7',
    'XunlaiWindow.StorageFrame.Tab8',
    'XunlaiWindow.StorageFrame.Tab9',
    'XunlaiWindow.StorageFrame.TabMaterialStorage',
}
