"""Frame aliases, keyed by engine frame name.

Key is "<name>" or "<name>,<code>,<code>,..." - the leading hash of the old
frame_aliases.json replaced by the frame name it resolves to (frame_names.py).
Value is the human label.

Generated - do not hand-edit.
"""

FRAME_ALIASES: dict[str, str] = {
    'NpcDialogue1': 'Dialogue 1',
    'NpcDialogue2': 'Dialogue 2',
    'SkillWarmup': 'Skill Warmup',
    'SkillUpkeep': 'Upkeep Monitor',
    'SkillTome': 'Skill Tome',
    'StatEnergy': 'Energy Bar',
    'StatHealth': 'Health Bar',
    'Bundle': 'Drop Bundle Button',
    'BtnExit': 'Close Window button',
    'BtnRestore': 'Restore Window Button',
    'BtnMin': 'Minimize Window Button',
    'BtnTrade': 'Trade Button',
    'Compass': 'Compass',
    'Effects': 'Effects Monitor',
    'Hint': 'Hints',
    'LevelProgress': 'Experience Bar',
    'MissionProgress': 'Mission Progress',
    'SkillBar': 'Skillbar',
    'WeaponBar': 'Weapon Bar',
    'Slot1': 'Set 1',
    'Slot2': 'Set 2',
    'Slot3': 'Set 3',
    'Slot4': 'Set 4',
    'Blurb': 'Mission Goals',
    'Chat': 'Chat',
    'BtnStateSwitch': 'Toggle Chat Button',
    'EditMessage': 'Text Area',
    'Filters': 'Chat Channels Toggle',
    'Log': 'Chat Log',
    'Tabs': 'Chat Channels',
    'DamageMonitor': 'Damage Monitor',
    'District': 'District List',
    'StClock': 'In-Game Clock',
    'MissionStatus': 'Mission Status and Score Display',
    'NotifyText': 'Notifications',
    'SkillMonitor': 'Skill Monitor',
    'Target': 'Target Display',
    'Party': 'Party Formation',
    'AgentCommander0': 'Hero 1 Window',
    'AgentCommander6': 'Hero 7 Window',
    'AgentCommander5': 'Hero 6 Window',
    'AgentCommander3': 'Hero 4 Window',
    'AgentCommander1': 'Hero 2 Window',
    'AgentCommander2': 'Hero 3 Window',
    'AgentCommander4': 'Hero 5 Window',
    'Attributes': 'Hero Window',
    'Guild': 'Guild Window',
    'DnStat': 'Performance Monitor',
    'StartMenuBar': 'Menu Button',
    'Options': 'Options Window',
    'HelpGuide': 'Help Window',
    'PartySearch': 'Party Search Window',
    'Friends': 'Friends Window',
    'ObserveSelect': 'Observe Window',
    'Quest': 'Quest Log Window',
    'DeckBuilder': 'Skills and Attributes Window',
    'InvAggregate': 'Inventory Bags Window',
    'Inventory': 'Inventory Window',
    'Slot5': 'Equipment Pack Slot',
    'Trash': 'Destroy Item Slot',
    'PartyBattle': 'Guild Battle Window',
    'SkillBar,6': 'Skillbar.Skill7',
    'SkillBar,6,2': 'Skillbar.Skill7.Frame',
    'SkillBar,6,2,6': 'Skillbar.Skill7.Frame.Number',
    'SkillBar,5': 'Skillbar.Skill6',
    'SkillBar,5,2': 'Skillbar.Skill6.Frame',
    'SkillBar,5,2,13': 'Skillbar.Skill6.Frame.Frame',
    'SkillBar,5,2,6': 'Skillbar.Skill6.Frame.Number',
    'SkillBar,7': 'Skillbar.Skill8',
    'SkillBar,7,2': 'Skillbar.Skill8.Frame',
    'SkillBar,7,2,6': 'Skillbar.Skill8.Frame.Number',
    'SkillBar,3': 'Skillbar.Skill4',
    'SkillBar,3,2': 'Skillbar.Skill4.Frame',
    'SkillBar,3,2,13': 'Skillbar.Skill4.Frame.Frame',
    'SkillBar,3,2,6': 'Skillbar.Skill4.Frame.Number',
    'SkillBar,4': 'Skillbar.Skill5',
    'SkillBar,4,2': 'Skillbar.Skill5.Frame',
    'SkillBar,4,2,6': 'Skillbar.Skill5.Frame.Number',
    'SkillBar,0': 'Skillbar.Skill1',
    'SkillBar,0,2': 'Skillbar.Skill1.Frame',
    'SkillBar,0,2,13': 'Skillbar.Skill1.Frame.Frame',
    'SkillBar,0,2,6': 'Skillbar.Skill1.Frame.Number',
    'SkillBar,1': 'Skillbar.Skill2',
    'SkillBar,1,2': 'Skillbar.Skill2.Frame',
    'SkillBar,1,2,6': 'Skillbar.Skill2.Frame.Number',
    'SkillBar,2': 'Skillbar.Skill3',
    'SkillBar,2,2': 'Skillbar.Skill3.Frame',
    'SkillBar,2,2,6': 'Skillbar.Skill3.Frame.Number',
    'StatEnergy,4': 'Energy Bar.Frame',
    'StatHealth,3': 'Healt Bar.Frame',
    'LevelProgress,1': 'Experience Bar.Frame',
    'Filters,5': 'Chat Channels Toggle.Emotes',
    'Filters,4': 'Chat Channels Toggle.Alliance',
    'Filters,3': 'Chat Channels Toggle.Trade',
    'Filters,2': 'Chat Channels Toggle.Team',
    'Filters,1': 'Chat Channels Toggle.Guild',
    'Filters,0': 'Chat Channels Toggle.Local',
    'Log,0': 'Chat Log.Frame',
    'Log,0,3': 'Chat Log.Frame.Scrollbar',
    'Log,0,0': 'Chat Log.Frame.Text',
    'Log,0,0,0': 'Chat Log.Frame.Text.TextArea',
    'Log,0,0,0,0': 'Chat Log.Frame.Text.TextArea.Line1',
    'Log,0,0,0,0,0': 'Chat Log.Frame.Text.TextArea.Line1.Text',
    'Log,0,0,0,0,0,2': 'Chat Log.Frame.Text.TextArea.Line1.Sender',
    'Tabs,3': 'Chat Channels.Team Text',
    'Tabs,0': 'Chat Channels.All Text',
    'Tabs,2': 'Chat Channels.Guild Text',
    'Tabs,4': 'Chat Channels.Trade Text',
    'Tabs,1': 'Chat Channels.Aliance Text',
    'Tabs,5': 'Chat Channels.Whisper Text',
    'EditName': 'Whisper Reciever',
    'Tabs,4294967295': 'Chat Channels.All',
    'Tabs,4294967293': 'Chat Channels.Guild',
    'Tabs,4294967292': 'Chat Channels.Team',
    'Tabs,4294967291': 'Chat Channels.Trade',
    'Tabs,4294967294': 'Chat Channels.Alliance',
    'Tabs,4294967290': 'Chat Channels.Whisper',
    'District,0': 'District List.Dropdown',
    'DnStat,0': 'Performance Monitor.Frame',
    'Game,6,126': 'Floating Button.Options',
    'Party,1': 'Party Formation.Frame.Outpost',
    'Party,1,4': 'Party Formation.Button Search',
    'Party,1,8': 'Party Formation.Party Members',
    'Party,1,8,0': 'Party Formation.Party Members.Frame',
    'Party,1,8,0,0,0,0,10,1': 'Party Formation.Ready Flag',
    'Party,1,8,0,0,0,0,10,0': 'Party Formation.Party Mebers.Player1',
    'Party,1,8,0,0,0,0,10,145': 'Party Formation.Party Members.Player2',
    'Party,1,8,0,0,0,0,10,145,0,2': 'Party Formation.Party Members.Player2.Player Name',
    'Party,1,8,0,0,0,0,10,145,0': 'Party Formation.Party Members.Player2.Frame',
    'Party,1,8,0,0,0,0,10,145,1': 'Party Formation.Party Members.Player2.Hero Window Toggle',
    'Party,1,8,0,0,0,0,10,142': 'Party Formation.Party Members.Player3',
    'Party,1,8,0,0,0,0,10,142,1': 'Party Formation.Party Members.Player3.Hero Window Toggle',
    'Party,1,8,0,0,0,0,10,110': 'Party Formation.Party Members.Player4',
    'Party,1,8,0,0,0,0,10,110,1': 'Party Formation.Party Members.Player4.Hero Window Toggle',
    'Party,1,8,0,0,0,0,10,121': 'Party Formation.Party Members.Player5',
    'Party,1,8,0,0,0,0,10,121,1': 'Party Formation.Party Members.Player5.Hero Window Toggle',
    'Party,1,8,0,0,0,0,10,116': 'Party Formation.Party Members.Player6',
    'Party,1,8,0,0,0,0,10,116,1': 'Party Formation.Party Members.Player6.Hero Window Toggle',
    'Party,1,8,0,0,0,0,10,104': 'Party Formation.Party Members.Player7',
    'Party,1,8,0,0,0,0,10,104,1': 'Party Formation.Party Members.Player7.Hero Window Toggle',
    'Party,1,8,0,0,0,0,10,94': 'Party Formation.Party Members.Player8',
    'Party,1,8,0,0,0,0,10,94,1': 'Party Formation.Party Members.Player8.Hero Window Toggle',
    'Party,1,1': 'Party Formation.Button Kick',
    'Party,1,2': 'Party Formation.Button Leave',
    'Party,1,7': 'Party Formation.Game Mode',
    'Party,1,7,0': 'Party Formation.Game Mode.Hard Mode',
    'Party,1,7,1': 'Party Formation.Game Mode.Normal Mode',
    'Party,1,7,2': 'Party Formation.Game Mode.Text',
    'Inventory,6': 'Inventory Window.Bags Bar',
    'Inventory,7': 'Inventory Window.Character Info',
    'Background': 'Inventory Window.Character Info.Frame',
    'ConfigEquipSets': 'Inventory Window.Character Info.Weapon Sets Button',
    'InvEquipSet': 'Enable Weapon Sets Window',
    'CheckF1': 'Enable Weapon Sets Window.Weapon Set 1',
    'CheckF3': 'Enable Weapon Sets Window.Weapon Set 3',
    'CheckF2': 'Enable Weapon Sets Window.Weapon Set 2',
    'CheckF4': 'Enable Weapon Sets Window.Weapon Set 4',
    'Text': 'Enable Weapon Sets Window.Label',
    'PrimaryHand': 'Inventory Window.Character Info.Weapon',
    'SecondaryHand': 'Inventory Window.Character Info.Offhand',
    'ChestArmor': 'Inventory Window.Character Info.Chest',
    'LegArmor': 'Inventory Window.Character Info.Pants',
    'Helm': 'Inventory Window.Character Info.Head',
    'Boots': 'Inventory Window.Character Info.Boots',
    'Gloves': 'Inventory Window.Character Info.Gloves',
    'Costume1': 'Inventory Window.Character Info.Costume',
    'Costume2': 'Inventory Window.Character Info.Costume Headpiece',
    'Gold': 'Inventory Window.Character Info.Gold Info',
    'Cape': 'Inventory Window.Character Info.Cape',
    'Gold,3': 'Inventory Window.Character Info.Gold Info.PlatinumQty',
    'Gold,2': 'Inventory Window.Character Info.Gold Info.GoldQty',
    'Gold,1': 'Inventory Window.Character Info.Gold Info.Platinum',
    'Gold,0': 'Inventory Window.Character Info.Gold Info.Gold',
    'VisCape': 'Inventory Window.Character Info.Toggle Cape',
    'VisHelm': 'Inventory Window.Character Info.Toggle Headpiece',
    'VisCostume1': 'Inventory Window.Character Info.Toggle Costume',
    'VisCostume2': 'Inventory Window.Character Info.Toggle Costume Headpiece',
    'Inventory,9': 'Inventory Window.Party Portraits',
    'Inventory,9,16777269': 'Inventory Window.Party Portraits.Player1',
    'Inventory,9,16777254': 'Inventory Window.Party Portraits.Player2',
    'Inventory,9,16777271': 'Inventory Window.Party Portraits.Player3',
    'Inventory,9,16777272': 'Inventory Window.Party Portraits.Player4',
    'Inventory,9,16777273': 'Inventory Window.Party Portraits.Player5',
    'Inventory,9,16777274': 'Inventory Window.Party Portraits.Player6',
    'Inventory,9,16777275': 'Inventory Window.Party Portraits.Player7',
    'Inventory,9,16777276': 'Inventory Window.Party Portraits.Player8',
    'BtnTrade,0': 'Trade Button.Button',
    'DlgTrade': 'Trade Window',
    'BtnCancel': 'Trade Window.Cancel Button',
    'TxtPartnerModifying': 'Trade Window.Offered Items',
    'GoldEditPlayer': 'Trade Window.Gold Offer',
    'GoldPartner': 'Trade Window.Gold Offered',
    'TxtPartnerOffer': 'Trade Window.Trade Partner',
    'CartPartner': 'Trade Window.Items Offered',
    'TxtPlayerOffer': 'Trade Window.Your Offer Label',
    'BtnModify': 'Trade Window.Submit Offer Button',
    'BtnAccept': 'Trade Window.Accept Button',
    'CartPlayer': 'Trade Window.Offered Items',
    'CartPlayer,1,0': 'Trade Window.Offered Items.Item1',
    'CartPlayer,1,1': 'Trade Window.Offered Items.Item2',
    'CartPlayer,1,2': 'Trade Window.Offered Items.Item3',
    'CartPlayer,1,3': 'Trade Window.Offered Items.Item4',
    'CartPlayer,1,4': 'Trade Window.Offered Items.Item5',
    'CartPlayer,1,5': 'Trade Window.Offered Items.Item6',
    'CartPlayer,1,6': 'Trade Window.Offered Items.Item7',
    'BtnView': 'Trade Window.View Button',
    'BtnDecline': 'Trade Window.Decline Button',
    'TxtPrompt': 'Trade Window.Caption',
    'InvAccount': 'Xunlai Window',
    'Game,6,113': 'Salvage Materials Dialog',
    'Game,6,113,4': 'Salvage Materials Dialog.No Button',
    'Game,6,113,0': 'Salvage Materials Dialog.Question Frame',
    'Game,6,113,6': 'Salvage Materials Dialog.Yes Button',
    'Game,6,113,1': 'Salvage Materials Dialog.Label',
    'Salvage': 'Salvage Window',
    'Salvage,2': 'Salvage Window.Salvage Button',
    'Salvage,3': 'Salvage Window,Salvage Details',
    'Salvage,1': 'Salvage Window.Cancel Button',
    'Salvage,4': 'Salvage Window.Header Label',
    'Salvage,5': 'Salvage Window.Options',
    'Salvage,5,0': 'Salvage Window.Options.Option1',
    'Salvage,5,1': 'Salvage Window.Options.Option2',
    'Salvage,5,2': 'Salvage Window.Options.Option3',
    'Salvage,5,3': 'Salvage Window.Options.Option4',
    'InvAccount,4': 'Xunlai Window.Withdraw Funds Button',
    'InvAccount,3': 'Xunlai Window.Deposit Funds Button',
    'InvAccount,0,4294967295': 'Xunlai Window.Tab1',
    'InvAccount,0,4294967285': 'Xunlai Window.Tab11',
    'InvAccount,0,4294967294': 'Xunlai Window.Tab2',
    'InvAccount,0,4294967281': 'Xunlai Window.Tab Material Storage',
    'InvAccount,0,4294967287': 'Xunlai Window.Tab9',
    'InvAccount,0,4294967289': 'Xunlai Window.Tab7',
    'InvAccount,0,4294967286': 'Xunlai Window.Tab10',
    'InvAccount,0,4294967284': 'Xunlai Window.Tab12',
    'InvAccount,0,4294967282': 'Xunlai Window.Tab14_AS',
    'InvAccount,0,4294967283': 'Xunlai Window.Tab13',
    'InvAccount,0,4294967290': 'Xunlai Window.Tab6',
    'InvAccount,0,4294967293': 'Xunlai Window.Tab3',
    'InvAccount,0,4294967292': 'Xunlai Window.Tab4',
    'InvAccount,0,4294967291': 'Xunlai Window.Tab5',
    'InvAccount,0,4294967288': 'Xunlai Window.Tab8',
    'NPCInteract': 'NPC Dialog',
    'NPCInteract,2,0,0,1': 'NPC Dialog.Option',
    'NPCInteract,2,3': 'NPC Dialog.Scroll_bar',
    'NPCInteract,2,0,0,1,2': 'NPC Dialog.Option1.Icon',
    'NPCInteract,2,0,0,1,1': 'NPC Dialog.Option2.Icon',
    'InvAggregate,0,0,0,0,2': 'Inventory Bags.Bag1.Slot1',
    'InvAggregate,0,0,0,0,3': 'Inventory Bags.Bag1.Slot2',
    'InvAggregate,0,0,0,0,4': 'Inventory Bags.Bag1.Slot3',
    'InvAggregate,0,0,0,0,5': 'Inventory Bags.Bag1.Slot4',
    'InvAggregate,0,0,0,0,6': 'Inventory Bags.Bag1.Slot5',
    'InvAggregate,0,0,0,0,7': 'Inventory Bags.Bag1.Slot6',
    'InvAggregate,0,0,0,0,8': 'Inventory Bags.Bag1.Slot7',
    'InvAggregate,0,0,0,0,9': 'Inventory Bags.Bag1.Slot8',
    'InvAggregate,0,0,0,0,10': 'Inventory Bags.Bag1.Slot9',
    'InvAggregate,0,0,0,0,11': 'Inventory Bags.Bag1.Slot10',
    'InvAggregate,0,0,0,0,12': 'Inventory Bags.Bag1.Slot11',
    'InvAggregate,0,0,0,0,13': 'Inventory Bags.Bag1.Slot12',
    'InvAggregate,0,0,0,0,14': 'Inventory Bags.Bag1.Slot13',
    'InvAggregate,0,0,0,0,15': 'Inventory Bags.Bag1.Slot14',
    'InvAggregate,0,0,0,0,16': 'Inventory Bags.Bag1.Slot15',
    'InvAggregate,0,0,0,0,17': 'Inventory Bags.Bag1.Slot16',
    'InvAggregate,0,0,0,0,18': 'Inventory Bags.Bag1.Slot17',
    'InvAggregate,0,0,0,0,19': 'Inventory Bags.Bag1.Slot18',
    'InvAggregate,0,0,0,0,20': 'Inventory Bags.Bag1.Slot19',
    'InvAggregate,0,0,0,0,21': 'Inventory Bags.Bag1.Slot20',
    'InvAggregate,0,0,0,1,2': 'Inventory Bags.Bag2.Slot1',
    'InvAggregate,0,0,0,1,3': 'Inventory Bags.Bag2.Slot2',
    'InvAggregate,0,0,0,1,4': 'Inventory Bags.Bag2.Slot3',
    'InvAggregate,0,0,0,1,5': 'Inventory Bags.Bag2.Slot4',
    'InvAggregate,0,0,0,1,6': 'Inventory Bags.Bag2.Slot5',
    'InvAggregate,0,0,0,2,2': 'Inventory Bags.Bag3.Slot1',
    'InvAggregate,0,0,0,2,3': 'Inventory Bags.Bag3.Slot2',
    'InvAggregate,0,0,0,2,4': 'Inventory Bags.Bag3.Slot3',
    'InvAggregate,0,0,0,2,5': 'Inventory Bags.Bag3.Slot4',
    'InvAggregate,0,0,0,2,6': 'Inventory Bags.Bag3.Slot5',
    'InvAggregate,0,0,0,2,7': 'Inventory Bags.Bag3.Slot6',
    'InvAggregate,0,0,0,2,8': 'Inventory Bags.Bag3.Slot7',
    'InvAggregate,0,0,0,2,9': 'Inventory Bags.Bag3.Slot8',
    'InvAggregate,0,0,0,2,10': 'Inventory Bags.Bag3.Slot9',
    'InvAggregate,0,0,0,2,11': 'Inventory Bags.Bag3.Slot10',
    'InvAggregate,0,0,0,3,2': 'Inventory Bags.Bag4.Slot1',
    'InvAggregate,0,0,0,3,3': 'Inventory Bags.Bag4.Slot2',
    'InvAggregate,0,0,0,3,4': 'Inventory Bags.Bag4.Slot3',
    'InvAggregate,0,0,0,3,5': 'Inventory Bags.Bag4.Slot4',
    'InvAggregate,0,0,0,3,6': 'Inventory Bags.Bag4.Slot5',
    'InvAggregate,0,0,0,3,7': 'Inventory Bags.Bag4.Slot6',
    'InvAggregate,0,0,0,3,8': 'Inventory Bags.Bag4.Slot7',
    'InvAggregate,0,0,0,3,9': 'Inventory Bags.Bag4.Slot8',
    'InvAggregate,0,0,0,3,11': 'Inventory Bags.Bag4.Slot10',
    'InvAggregate,0,0,0,3,10': 'Inventory Bags.Bag4.Slot9',
    'NPCInteract,1': 'Use Lockpick Button',
    'Party,0': 'Party Formation.Frame.Explorable',
    'InvAccount,1': 'Xunlai Window.Gold Frame',
    'InvAccount,0,0,2': 'Xunlai Window.Tab1.Item1',
    'InvAccount,0,0,3': 'Xunlai Window.Tab1.Item2',
    'InvAccount,0,0,4': 'Xunlai Window.Tab1.Item3',
    'InvAccount,0,0,5': 'Xunlai Window.Tab1.Item4',
    'InvAccount,0,0,6': 'Xunlai Window.Tab1.Item5',
    'InvAccount,0,0,7': 'Xunlai Window.Tab1.Item6',
    'InvAccount,0,0,8': 'Xunlai Window.Tab1.Item7',
    'InvAccount,0,0,9': 'Xunlai Window.Tab1.Item8',
    'InvAccount,0,0,10': 'Xunlai Window.Tab1.Item9',
    'InvAccount,0,0,11': 'Xunlai Window.Tab1.Item10',
    'InvAccount,0,0': 'Xunlai Window.Tab1.Content',
    'InvAccount,0,0,12': 'Xunlai Window.Tab1.Item11',
    'InvAccount,0,0,13': 'Xunlai Window.Tab1.Item12',
    'InvAccount,0,0,14': 'Xunlai Window.Tab1.Item13',
    'InvAccount,0,0,15': 'Xunlai Window.Tab1.Item14',
    'InvAccount,0,0,16': 'Xunlai Window.Tab1.Item15',
    'InvAccount,0,0,17': 'Xunlai Window.Tab1.Item16',
    'InvAccount,0,0,18': 'Xunlai Window.Tab1.Item17',
    'InvAccount,0,0,19': 'Xunlai Window.Tab1.Item18',
    'InvAccount,0,0,20': 'Xunlai Window.Tab1.Item19',
    'InvAccount,0,0,21': 'Xunlai Window.Tab1.Item20',
    'InvAccount,0,0,22': 'Xunlai Window.Tab1.Item21',
    'InvAccount,0,0,23': 'Xunlai Window.Tab1.Item22',
    'InvAccount,0,0,24': 'Xunlai Window.Tab1.Item23',
    'InvAccount,0,0,25': 'Xunlai Window.Tab1.Item24',
    'InvAccount,0,0,26': 'Xunlai Window.Tab1.Item25',
    'InvAccount,0,1': 'Xunlai Window.Tab2.Content',
    'InvAccount,0,1,2': 'Xunlai Window.Tab2.Item1',
    'InvAccount,0,1,3': 'Xunlai Window.Tab2.Item2',
    'InvAccount,0,1,4': 'Xunlai Window.Tab2.Item3',
    'InvAccount,0,1,5': 'Xunlai Window.Tab2.Item4',
    'InvAccount,0,1,6': 'Xunlai Window.Tab2.Item5',
    'InvAccount,0,1,7': 'Xunlai Window.Tab2.Item6',
    'InvAccount,0,1,8': 'Xunlai Window.Tab2.Item7',
    'InvAccount,0,1,9': 'Xunlai Window.Tab2.Item8',
    'InvAccount,0,1,10': 'Xunlai Window.Tab2.Item9',
    'InvAccount,0,1,11': 'Xunlai Window.Tab2.Item10',
    'InvAccount,0,1,12': 'Xunlai Window.Tab2.Item11',
    'InvAccount,0,1,13': 'Xunlai Window.Tab2.Item12',
    'InvAccount,0,1,14': 'Xunlai Window.Tab2.Item13',
    'InvAccount,0,1,15': 'Xunlai Window.Tab2.Item14',
    'InvAccount,0,1,16': 'Xunlai Window.Tab2.Item15',
    'InvAccount,0,1,17': 'Xunlai Window.Tab2.Item16',
    'InvAccount,0,1,18': 'Xunlai Window.Tab2.Item17',
    'InvAccount,0,1,19': 'Xunlai Window.Tab2.Item18',
    'InvAccount,0,1,20': 'Xunlai Window.Tab2.Item19',
    'InvAccount,0,1,21': 'Xunlai Window.Tab2.Item20',
    'InvAccount,0,1,22': 'Xunlai Window.Tab2.Item21',
    'InvAccount,0,1,23': 'Xunlai Window.Tab2.Item22',
    'InvAccount,0,1,24': 'Xunlai Window.Tab2.Item23',
    'InvAccount,0,1,25': 'Xunlai Window.Tab2.Item24',
    'InvAccount,0,1,26': 'Xunlai Window.Tab2.Item25',
    'InvAccount,0,2': 'Xunlai Window.Tab3.Content',
    'InvAccount,0,2,2': 'Xunlai Window.Tab3.Item1',
    'InvAccount,0,2,3': 'Xunlai Window.Tab3.Item2',
    'InvAccount,0,2,4': 'Xunlai Window.Tab3.Item3',
    'InvAccount,0,2,5': 'Xunlai Window.Tab3.Item4',
    'InvAccount,0,2,6': 'Xunlai Window.Tab3.Item5',
    'InvAccount,0,2,7': 'Xunlai Window.Tab3.Item6',
    'InvAccount,0,2,8': 'Xunlai Window.Tab3.Item7',
    'InvAccount,0,2,9': 'Xunlai Window.Tab3.Item8',
    'InvAccount,0,2,10': 'Xunlai Window.Tab3.Item9',
    'InvAccount,0,2,11': 'Xunlai Window.Tab3.Item10',
    'InvAccount,0,2,12': 'Xunlai Window.Tab3.Item11',
    'InvAccount,0,2,13': 'Xunlai Window.Tab3.Item12',
    'InvAccount,0,2,14': 'Xunlai Window.Tab3.Item13',
    'InvAccount,0,2,15': 'Xunlai Window.Tab3.Item14',
    'InvAccount,0,2,16': 'Xunlai Window.Tab3.Item15',
    'InvAccount,0,2,17': 'Xunlai Window.Tab3.Item16',
    'InvAccount,0,2,18': 'Xunlai Window.Tab3.Item17',
    'InvAccount,0,2,19': 'Xunlai Window.Tab3.Item18',
    'InvAccount,0,2,20': 'Xunlai Window.Tab3.Item19',
    'InvAccount,0,2,21': 'Xunlai Window.Tab3.Item20',
    'InvAccount,0,2,22': 'Xunlai Window.Tab3.Item21',
    'InvAccount,0,2,23': 'Xunlai Window.Tab3.Item22',
    'InvAccount,0,2,24': 'Xunlai Window.Tab3.Item23',
    'InvAccount,0,2,25': 'Xunlai Window.Tab3.Item24',
    'InvAccount,0,2,26': 'Xunlai Window.Tab3.Item25',
    'InvAccount,0,3': 'Xunlai Window.Tab4.Content',
    'InvAccount,0,3,2': 'Xunlai Window.Tab4.Item1',
    'InvAccount,0,3,3': 'Xunlai Window.Tab4.Item2',
    'InvAccount,0,3,4': 'Xunlai Window.Tab4.Item3',
    'InvAccount,0,3,5': 'Xunlai Window.Tab4.Item4',
    'InvAccount,0,3,6': 'Xunlai Window.Tab4.Item5',
    'InvAccount,0,3,7': 'Xunlai Window.Tab4.Item6',
    'InvAccount,0,3,8': 'Xunlai Window.Tab4.Item7',
    'InvAccount,0,3,9': 'Xunlai Window.Tab4.Item8',
    'InvAccount,0,3,10': 'Xunlai Window.Tab4.Item9',
    'InvAccount,0,3,11': 'Xunlai Window.Tab4.Item10',
    'InvAccount,0,3,12': 'Xunlai Window.Tab4.Item11',
    'InvAccount,0,3,13': 'Xunlai Window.Tab4.Item12',
    'InvAccount,0,3,14': 'Xunlai Window.Tab4.Item13',
    'InvAccount,0,3,15': 'Xunlai Window.Tab4.Item14',
    'InvAccount,0,3,16': 'Xunlai Window.Tab4.Item15',
    'InvAccount,0,3,17': 'Xunlai Window.Tab4.Item16',
    'InvAccount,0,3,18': 'Xunlai Window.Tab4.Item17',
    'InvAccount,0,3,19': 'Xunlai Window.Tab4.Item18',
    'InvAccount,0,3,20': 'Xunlai Window.Tab4.Item19',
    'InvAccount,0,3,21': 'Xunlai Window.Tab4.Item20',
    'InvAccount,0,3,22': 'Xunlai Window.Tab4.Item21',
    'InvAccount,0,3,23': 'Xunlai Window.Tab4.Item22',
    'InvAccount,0,3,24': 'Xunlai Window.Tab4.Item23',
    'InvAccount,0,3,25': 'Xunlai Window.Tab4.Item24',
    'InvAccount,0,3,26': 'Xunlai Window.Tab4.Item25',
    'InvAccount,0,4': 'Xunlai Window.Tab5.Content',
    'InvAccount,0,4,2': 'Xunlai Window.Tab5.Item1',
    'InvAccount,0,4,3': 'Xunlai Window.Tab5.Item2',
    'InvAccount,0,4,4': 'Xunlai Window.Tab5.Item3',
    'InvAccount,0,4,5': 'Xunlai Window.Tab5.Item4',
    'InvAccount,0,4,6': 'Xunlai Window.Tab5.Item5',
    'InvAccount,0,4,7': 'Xunlai Window.Tab5.Item6',
    'InvAccount,0,4,8': 'Xunlai Window.Tab5.Item7',
    'InvAccount,0,4,9': 'Xunlai Window.Tab5.Item8',
    'InvAccount,0,4,10': 'Xunlai Window.Tab5.Item9',
    'InvAccount,0,4,11': 'Xunlai Window.Tab5.Item10',
    'InvAccount,0,4,12': 'Xunlai Window.Tab5.Item11',
    'InvAccount,0,4,13': 'Xunlai Window.Tab5.Item12',
    'InvAccount,0,4,14': 'Xunlai Window.Tab5.Item13',
    'InvAccount,0,4,15': 'Xunlai Window.Tab5.Item14',
    'InvAccount,0,4,16': 'Xunlai Window.Tab5.Item15',
    'InvAccount,0,4,17': 'Xunlai Window.Tab5.Item16',
    'InvAccount,0,4,18': 'Xunlai Window.Tab5.Item17',
    'InvAccount,0,4,19': 'Xunlai Window.Tab5.Item18',
    'InvAccount,0,4,20': 'Xunlai Window.Tab5.Item19',
    'InvAccount,0,4,21': 'Xunlai Window.Tab5.Item20',
    'InvAccount,0,4,22': 'Xunlai Window.Tab5.Item21',
    'InvAccount,0,4,23': 'Xunlai Window.Tab5.Item22',
    'InvAccount,0,4,24': 'Xunlai Window.Tab5.Item23',
    'InvAccount,0,4,25': 'Xunlai Window.Tab5.Item24',
    'InvAccount,0,4,26': 'Xunlai Window.Tab5.Item25',
    'InvAccount,0,14': 'Xunlai Window.Tab Material Storage.Content',
    'InvAccount,0,14,8': 'Xunlai Window.Tab Material Storage.Bones',
    'InvAccount,0,14,1': 'Xunlai Window.Tab Material Storage.Iron',
    'InvAccount,0,14,3': 'Xunlai Window.Tab Material Storage.Tanned_Hide',
    'InvAccount,0,14,6': 'Xunlai Window.Tab Material Storage.Scale',
    'InvAccount,0,14,7': 'Xunlai Window.Tab Material Storage.Chitin',
    'InvAccount,0,14,2': 'Xunlai Window.Tab Material Storage.Cloth',
    'InvAccount,0,14,4': 'Xunlai Window.Tab Material Storage.Wood',
    'InvAccount,0,14,9': 'Xunlai Window.Tab Material Storage.Granite',
    'InvAccount,0,14,5': 'Xunlai Window.Tab Material Storage.Dust',
    'InvAccount,0,14,10': 'Xunlai Window.Tab Material Storage.Plant_Fibers',
    'InvAccount,0,14,11': 'Xunlai Window.Tab Material Storage.Feather',
    'InvAccount,0,14,12': 'Xunlai Window.Tab Material Storage.Fur',
    'InvAccount,0,14,13': 'Xunlai Window.Tab Material Storage.Linen',
    'InvAccount,0,14,14': 'Xunlai Window.Tab Material Storage.Damask',
    'InvAccount,0,14,15': 'Xunlai Window.Tab Material Storage.Silk',
    'InvAccount,0,14,16': 'Xunlai Window.Tab Material Storage.Ectoplasm',
    'InvAccount,0,14,17': 'Xunlai Window.Tab Material Storage.Steel',
    'InvAccount,0,14,18': 'Xunlai Window.Tab Material Storage.Deldrimor_Steel',
    'InvAccount,0,14,19': 'Xunlai Window.Tab Material Storage.Monstrous_Claws',
    'InvAccount,0,14,20': 'Xunlai Window.Tab Material Storage.Monstrous_Eye',
    'InvAccount,0,14,21': 'Xunlai Window.Tab Material Storage.Monstrous_Fang',
    'InvAccount,0,14,23': 'Xunlai Window.Tab Material Storage.Ruby',
    'InvAccount,0,14,24': 'Xunlai Window.Tab Material Storage.Sapphire',
    'InvAccount,0,14,22': 'Xunlai Window.Tab Material Storage.Diamond',
    'InvAccount,0,14,36': 'Xunlai Window.Tab Material Storage.Onyx',
    'InvAccount,0,14,28': 'Xunlai Window.Tab Material Storage.Charcoal',
    'InvAccount,0,14,25': 'Xunlai Window.Tab Material Storage.Obsidian_Shard',
    'InvAccount,0,14,29': 'Xunlai Window.Tab Material Storage.Glass_Vial',
    'InvAccount,0,14,30': 'Xunlai Window.Tab Material Storage.Leather',
    'InvAccount,0,14,31': 'Xunlai Window.Tab Material Storage.Elonian_Leather',
    'InvAccount,0,14,32': 'Xunlai Window.Tab Material Storage.Ink',
    'InvAccount,0,14,33': 'Xunlai Window.Tab Material Storage.Parchment',
    'InvAccount,0,14,34': 'Xunlai Window.Tab Material Storage.Vellum',
    'InvAccount,0,14,35': 'Xunlai Window.Tab Material Storage.Spiritwood',
    'InvAccount,0,14,26': 'Xunlai Window.Tab Material Storage.Amber',
    'InvAccount,0,14,27': 'Xunlai Window.Tab Material Storage.Jadeite',
    'InvAccount,0': 'Xunlai Window.StorageFrame',
    'InvAccount,0,13': 'Xunlai Window.Tab14_AS.Content',
    'InvAccount,0,13,3': 'Xunlai Window.Tab14_AS.Item2',
    'InvAccount,0,13,5': 'Xunlai Window.Tab14_AS.Item4',
    'InvAccount,0,13,7': 'Xunlai Window.Tab14_AS.Item6',
    'InvAccount,0,13,9': 'Xunlai Window.Tab14_AS.Item8',
    'InvAccount,0,13,11': 'Xunlai Window.Tab14_AS.Item10',
    'InvAccount,0,13,13': 'Xunlai Window.Tab14_AS.Item12',
    'InvAccount,0,13,15': 'Xunlai Window.Tab14_AS.Item14',
    'InvAccount,0,13,17': 'Xunlai Window.Tab14_AS.Item16',
    'InvAccount,0,13,19': 'Xunlai Window.Tab14_AS.Item18',
    'InvAccount,0,13,21': 'Xunlai Window.Tab14_AS.Item20',
    'InvAccount,0,13,23': 'Xunlai Window.Tab14_AS.Item22',
    'InvAccount,0,13,25': 'Xunlai Window.Tab14_AS.Item24',
    'InvAccount,0,13,26': 'Xunlai Window.Tab14_AS.Item25',
    'InvAccount,0,13,8': 'Xunlai Window.Tab14_AS.Item7',
    'InvAccount,0,13,10': 'Xunlai Window.Tab14_AS.Item9',
    'InvAccount,0,13,12': 'Xunlai Window.Tab14_AS.Item11',
    'InvAccount,0,13,20': 'Xunlai Window.Tab14_AS.Item19',
    'InvAccount,0,13,22': 'Xunlai Window.Tab14_AS.Item21',
    'InvAccount,0,13,24': 'Xunlai Window.Tab14_AS.Item23',
    'InvAccount,0,13,2': 'Xunlai Window.Tab14_AS.Item1',
    'InvAccount,0,13,4': 'Xunlai Window.Tab14_AS.Item3',
    'InvAccount,0,13,6': 'Xunlai Window.Tab14_AS.Item5',
    'InvAccount,0,13,14': 'Xunlai Window.Tab14_AS.Item13',
    'InvAccount,0,13,16': 'Xunlai Window.Tab14_AS.Item15',
    'InvAccount,0,13,18': 'Xunlai Window.Tab14_AS.Item17',
    'InvAccount,0,12': 'Xunlai Window.Tab13.Content',
    'InvAccount,0,12,2': 'Xunlai Window.Tab13.Item1',
    'InvAccount,0,12,3': 'Xunlai Window.Tab13.Item2',
    'InvAccount,0,12,4': 'Xunlai Window.Tab13.Item3',
    'InvAccount,0,12,6': 'Xunlai Window.Tab13.Item5',
    'InvAccount,0,12,8': 'Xunlai Window.Tab13.Item7',
    'InvAccount,0,12,10': 'Xunlai Window.Tab13.Item9',
    'InvAccount,0,12,12': 'Xunlai Window.Tab13.Item11',
    'InvAccount,0,12,14': 'Xunlai Window.Tab13.Item13',
    'InvAccount,0,12,16': 'Xunlai Window.Tab13.Item15',
    'InvAccount,0,12,18': 'Xunlai Window.Tab13.Item17',
    'InvAccount,0,12,20': 'Xunlai Window.Tab13.Item19',
    'InvAccount,0,12,22': 'Xunlai Window.Tab13.Item21',
    'InvAccount,0,12,24': 'Xunlai Window.Tab13.Item23',
    'InvAccount,0,12,26': 'Xunlai Window.Tab13.Item25',
    'InvAccount,0,12,17': 'Xunlai Window.Tab13.Item16',
    'InvAccount,0,12,19': 'Xunlai Window.Tab13.Item18',
    'InvAccount,0,12,21': 'Xunlai Window.Tab13.Item20',
    'InvAccount,0,12,11': 'Xunlai Window.Tab13.Item10',
    'InvAccount,0,12,13': 'Xunlai Window.Tab13.Item12',
    'InvAccount,0,12,15': 'Xunlai Window.Tab13.Item14',
    'InvAccount,0,12,5': 'Xunlai Window.Tab13.Item4',
    'InvAccount,0,12,7': 'Xunlai Window.Tab13.Item6',
    'InvAccount,0,12,9': 'Xunlai Window.Tab13.Item8',
    'InvAccount,0,12,23': 'Xunlai Window.Tab13.Item22',
    'InvAccount,0,12,25': 'Xunlai Window.Tab13.Item24',
    'InvAccount,0,11': 'Xunlai Window.Tab12.Content',
    'InvAccount,0,10': 'Xunlai Window.Tab11.Content',
    'InvAccount,0,9': 'Xunlai Window.Tab10.Content',
    'InvAccount,0,8': 'Xunlai Window.Tab9.Content',
    'InvAccount,0,7': 'Xunlai Window.Tab8.Content',
    'InvAccount,0,6': 'Xunlai Window.Tab7.Content',
    'InvAccount,0,5': 'Xunlai Window.Tab6.Content',
    'InvAccount,0,11,2': 'Xunlai Window.Tab12.Item1',
    'InvAccount,0,11,3': 'Xunlai Window.Tab12.Item2',
    'InvAccount,0,11,4': 'Xunlai Window.Tab12.Item3',
    'InvAccount,0,11,5': 'Xunlai Window.Tab12.Item4',
    'InvAccount,0,11,6': 'Xunlai Window.Tab12.Item5',
    'InvAccount,0,11,7': 'Xunlai Window.Tab12.Item6',
    'InvAccount,0,11,8': 'Xunlai Window.Tab12.Item7',
    'InvAccount,0,11,9': 'Xunlai Window.Tab12.Item8',
    'InvAccount,0,11,10': 'Xunlai Window.Tab12.Item9',
    'InvAccount,0,11,11': 'Xunlai Window.Tab12.Item10',
    'InvAccount,0,11,12': 'Xunlai Window.Tab12.Item11',
    'InvAccount,0,11,13': 'Xunlai Window.Tab12.Item12',
    'InvAccount,0,11,14': 'Xunlai Window.Tab12.Item13',
    'InvAccount,0,11,15': 'Xunlai Window.Tab12.Item14',
    'InvAccount,0,11,16': 'Xunlai Window.Tab12.Item15',
    'InvAccount,0,11,17': 'Xunlai Window.Tab12.Item16',
    'InvAccount,0,11,18': 'Xunlai Window.Tab12.Item17',
    'InvAccount,0,11,19': 'Xunlai Window.Tab12.Item18',
    'InvAccount,0,11,20': 'Xunlai Window.Tab12.Item19',
    'InvAccount,0,11,21': 'Xunlai Window.Tab12.Item20',
    'InvAccount,0,11,22': 'Xunlai Window.Tab12.Item21',
    'InvAccount,0,11,23': 'Xunlai Window.Tab12.Item22',
    'InvAccount,0,11,24': 'Xunlai Window.Tab12.Item23',
    'InvAccount,0,11,25': 'Xunlai Window.Tab12.Item24',
    'InvAccount,0,11,26': 'Xunlai Window.Tab12.Item25',
    'InvAccount,0,10,2': 'Xunlai Window.Tab11.Item1',
    'InvAccount,0,10,3': 'Xunlai Window.Tab11.Item2',
    'InvAccount,0,10,4': 'Xunlai Window.Tab11.Item3',
    'InvAccount,0,10,5': 'Xunlai Window.Tab11.Item4',
    'InvAccount,0,10,6': 'Xunlai Window.Tab11.Item5',
    'InvAccount,0,10,7': 'Xunlai Window.Tab11.Item6',
    'InvAccount,0,10,8': 'Xunlai Window.Tab11.Item7',
    'InvAccount,0,10,9': 'Xunlai Window.Tab11.Item8',
    'InvAccount,0,10,10': 'Xunlai Window.Tab11.Item9',
    'InvAccount,0,10,11': 'Xunlai Window.Tab11.Item10',
    'InvAccount,0,10,12': 'Xunlai Window.Tab11.Item11',
    'InvAccount,0,10,13': 'Xunlai Window.Tab11.Item12',
    'InvAccount,0,10,14': 'Xunlai Window.Tab11.Item13',
    'InvAccount,0,10,15': 'Xunlai Window.Tab11.Item14',
    'InvAccount,0,10,16': 'Xunlai Window.Tab11.Item15',
    'InvAccount,0,10,17': 'Xunlai Window.Tab11.Item16',
    'InvAccount,0,10,18': 'Xunlai Window.Tab11.Item17',
    'InvAccount,0,10,19': 'Xunlai Window.Tab11.Item18',
    'InvAccount,0,10,20': 'Xunlai Window.Tab11.Item19',
    'InvAccount,0,10,21': 'Xunlai Window.Tab11.Item20',
    'InvAccount,0,10,22': 'Xunlai Window.Tab11.Item21',
    'InvAccount,0,10,23': 'Xunlai Window.Tab11.Item22',
    'InvAccount,0,10,24': 'Xunlai Window.Tab11.Item23',
    'InvAccount,0,10,25': 'Xunlai Window.Tab11.Item24',
    'InvAccount,0,10,26': 'Xunlai Window.Tab11.Item25',
    'InvAccount,0,9,2': 'Xunlai Window.Tab10.Item1',
    'InvAccount,0,9,3': 'Xunlai Window.Tab10.Item2',
    'InvAccount,0,9,4': 'Xunlai Window.Tab10.Item3',
    'InvAccount,0,9,5': 'Xunlai Window.Tab10.Item4',
    'InvAccount,0,9,6': 'Xunlai Window.Tab10.Item5',
    'InvAccount,0,9,7': 'Xunlai Window.Tab10.Item6',
    'InvAccount,0,9,8': 'Xunlai Window.Tab10.Item7',
    'InvAccount,0,9,9': 'Xunlai Window.Tab10.Item8',
    'InvAccount,0,9,10': 'Xunlai Window.Tab10.Item9',
    'InvAccount,0,9,11': 'Xunlai Window.Tab10.Item10',
    'InvAccount,0,9,12': 'Xunlai Window.Tab10.Item11',
    'InvAccount,0,9,13': 'Xunlai Window.Tab10.Item12',
    'InvAccount,0,9,14': 'Xunlai Window.Tab10.Item13',
    'InvAccount,0,9,15': 'Xunlai Window.Tab10.Item14',
    'InvAccount,0,9,16': 'Xunlai Window.Tab10.Item15',
    'InvAccount,0,9,17': 'Xunlai Window.Tab10.Item16',
    'InvAccount,0,9,18': 'Xunlai Window.Tab10.Item17',
    'InvAccount,0,9,19': 'Xunlai Window.Tab10.Item18',
    'InvAccount,0,9,20': 'Xunlai Window.Tab10.Item19',
    'InvAccount,0,9,21': 'Xunlai Window.Tab10.Item20',
    'InvAccount,0,9,22': 'Xunlai Window.Tab10.Item21',
    'InvAccount,0,9,23': 'Xunlai Window.Tab10.Item22',
    'InvAccount,0,9,24': 'Xunlai Window.Tab10.Item23',
    'InvAccount,0,9,25': 'Xunlai Window.Tab10.Item24',
    'InvAccount,0,9,26': 'Xunlai Window.Tab10.Item25',
    'InvAccount,0,8,2': 'Xunlai Window.Tab9.Item1',
    'InvAccount,0,8,3': 'Xunlai Window.Tab9.Item2',
    'InvAccount,0,8,4': 'Xunlai Window.Tab9.Item3',
    'InvAccount,0,8,5': 'Xunlai Window.Tab9.Item4',
    'InvAccount,0,8,6': 'Xunlai Window.Tab9.Item5',
    'InvAccount,0,8,7': 'Xunlai Window.Tab9.Item6',
    'InvAccount,0,8,8': 'Xunlai Window.Tab9.Item7',
    'InvAccount,0,8,9': 'Xunlai Window.Tab9.Item8',
    'InvAccount,0,8,10': 'Xunlai Window.Tab9.Item9',
    'InvAccount,0,8,11': 'Xunlai Window.Tab9.Item10',
    'InvAccount,0,8,12': 'Xunlai Window.Tab9.Item11',
    'InvAccount,0,8,13': 'Xunlai Window.Tab9.Item12',
    'InvAccount,0,8,14': 'Xunlai Window.Tab9.Item13',
    'InvAccount,0,8,15': 'Xunlai Window.Tab9.Item14',
    'InvAccount,0,8,16': 'Xunlai Window.Tab9.Item15',
    'InvAccount,0,8,17': 'Xunlai Window.Tab9.Item16',
    'InvAccount,0,8,18': 'Xunlai Window.Tab9.Item17',
    'InvAccount,0,8,19': 'Xunlai Window.Tab9.Item18',
    'InvAccount,0,8,20': 'Xunlai Window.Tab9.Item19',
    'InvAccount,0,8,21': 'Xunlai Window.Tab9.Item20',
    'InvAccount,0,8,22': 'Xunlai Window.Tab9.Item21',
    'InvAccount,0,8,23': 'Xunlai Window.Tab9.Item22',
    'InvAccount,0,8,24': 'Xunlai Window.Tab9.Item23',
    'InvAccount,0,8,25': 'Xunlai Window.Tab9.Item24',
    'InvAccount,0,8,26': 'Xunlai Window.Tab9.Item25',
    'InvAccount,0,7,2': 'Xunlai Window.Tab8.Item1',
    'InvAccount,0,7,3': 'Xunlai Window.Tab8.Item2',
    'InvAccount,0,7,4': 'Xunlai Window.Tab8.Item3',
    'InvAccount,0,7,5': 'Xunlai Window.Tab8.Item4',
    'InvAccount,0,7,6': 'Xunlai Window.Tab8.Item5',
    'InvAccount,0,7,7': 'Xunlai Window.Tab8.Item6',
    'InvAccount,0,7,8': 'Xunlai Window.Tab8.Item7',
    'InvAccount,0,7,9': 'Xunlai Window.Tab8.Item8',
    'InvAccount,0,7,10': 'Xunlai Window.Tab8.Item9',
    'InvAccount,0,7,11': 'Xunlai Window.Tab8.Item10',
    'InvAccount,0,7,12': 'Xunlai Window.Tab8.Item11',
    'InvAccount,0,7,13': 'Xunlai Window.Tab8.Item12',
    'InvAccount,0,7,14': 'Xunlai Window.Tab8.Item13',
    'InvAccount,0,7,15': 'Xunlai Window.Tab8.Item14',
    'InvAccount,0,7,16': 'Xunlai Window.Tab8.Item15',
    'InvAccount,0,7,17': 'Xunlai Window.Tab8.Item16',
    'InvAccount,0,7,18': 'Xunlai Window.Tab8.Item17',
    'InvAccount,0,7,19': 'Xunlai Window.Tab8.Item18',
    'InvAccount,0,7,20': 'Xunlai Window.Tab8.Item19',
    'InvAccount,0,7,21': 'Xunlai Window.Tab8.Item20',
    'InvAccount,0,7,22': 'Xunlai Window.Tab8.Item21',
    'InvAccount,0,7,23': 'Xunlai Window.Tab8.Item22',
    'InvAccount,0,7,24': 'Xunlai Window.Tab8.Item23',
    'InvAccount,0,7,25': 'Xunlai Window.Tab8.Item24',
    'InvAccount,0,7,26': 'Xunlai Window.Tab8.Item25',
    'InvAccount,0,6,2': 'Xunlai Window.Tab7.Item1',
    'InvAccount,0,6,3': 'Xunlai Window.Tab7.Item2',
    'InvAccount,0,6,4': 'Xunlai Window.Tab7.Item3',
    'InvAccount,0,6,5': 'Xunlai Window.Tab7.Item4',
    'InvAccount,0,6,6': 'Xunlai Window.Tab7.Item5',
    'InvAccount,0,6,7': 'Xunlai Window.Tab7.Item6',
    'InvAccount,0,6,8': 'Xunlai Window.Tab7.Item7',
    'InvAccount,0,6,9': 'Xunlai Window.Tab7.Item8',
    'InvAccount,0,6,10': 'Xunlai Window.Tab7.Item9',
    'InvAccount,0,6,11': 'Xunlai Window.Tab7.Item10',
    'InvAccount,0,6,12': 'Xunlai Window.Tab7.Item11',
    'InvAccount,0,6,13': 'Xunlai Window.Tab7.Item12',
    'InvAccount,0,6,14': 'Xunlai Window.Tab7.Item13',
    'InvAccount,0,6,15': 'Xunlai Window.Tab7.Item14',
    'InvAccount,0,6,16': 'Xunlai Window.Tab7.Item15',
    'InvAccount,0,6,17': 'Xunlai Window.Tab7.Item16',
    'InvAccount,0,6,18': 'Xunlai Window.Tab7.Item17',
    'InvAccount,0,6,19': 'Xunlai Window.Tab7.Item18',
    'InvAccount,0,6,20': 'Xunlai Window.Tab7.Item19',
    'InvAccount,0,6,21': 'Xunlai Window.Tab7.Item20',
    'InvAccount,0,6,22': 'Xunlai Window.Tab7.Item21',
    'InvAccount,0,6,23': 'Xunlai Window.Tab7.Item22',
    'InvAccount,0,6,24': 'Xunlai Window.Tab7.Item23',
    'InvAccount,0,6,25': 'Xunlai Window.Tab7.Item24',
    'InvAccount,0,6,26': 'Xunlai Window.Tab7.Item25',
    'InvAccount,0,5,2': 'Xunlai Window.Tab6.Item1',
    'InvAccount,0,5,3': 'Xunlai Window.Tab6.Item2',
    'InvAccount,0,5,4': 'Xunlai Window.Tab6.Item3',
    'InvAccount,0,5,5': 'Xunlai Window.Tab6.Item4',
    'InvAccount,0,5,6': 'Xunlai Window.Tab6.Item5',
    'InvAccount,0,5,7': 'Xunlai Window.Tab6.Item6',
    'InvAccount,0,5,8': 'Xunlai Window.Tab6.Item7',
    'InvAccount,0,5,9': 'Xunlai Window.Tab6.Item8',
    'InvAccount,0,5,10': 'Xunlai Window.Tab6.Item9',
    'InvAccount,0,5,11': 'Xunlai Window.Tab6.Item10',
    'InvAccount,0,5,12': 'Xunlai Window.Tab6.Item11',
    'InvAccount,0,5,13': 'Xunlai Window.Tab6.Item12',
    'InvAccount,0,5,14': 'Xunlai Window.Tab6.Item13',
    'InvAccount,0,5,15': 'Xunlai Window.Tab6.Item14',
    'InvAccount,0,5,16': 'Xunlai Window.Tab6.Item15',
    'InvAccount,0,5,17': 'Xunlai Window.Tab6.Item16',
    'InvAccount,0,5,18': 'Xunlai Window.Tab6.Item17',
    'InvAccount,0,5,19': 'Xunlai Window.Tab6.Item18',
    'InvAccount,0,5,20': 'Xunlai Window.Tab6.Item19',
    'InvAccount,0,5,21': 'Xunlai Window.Tab6.Item20',
    'InvAccount,0,5,22': 'Xunlai Window.Tab6.Item21',
    'InvAccount,0,5,23': 'Xunlai Window.Tab6.Item22',
    'InvAccount,0,5,24': 'Xunlai Window.Tab6.Item23',
    'InvAccount,0,5,25': 'Xunlai Window.Tab6.Item24',
    'InvAccount,0,5,26': 'Xunlai Window.Tab6.Item25',
    'InvAggregate,0,0,0,0': 'Inventory Bags.Bag1',
    'Game,6,1': 'Screen Frame',
    'Game,6,50331676,0': '',
    'Game,6,50331676': 'NPC Nameplate Frame',
    'Game,6,50331675': 'NPC Nameplate Frame',
    'Game,6,50331675,0': 'NPC Nameplate Frame',
    'Game,6,50331674': 'NPC Nameplate Frame',
    'Game,6,50331674,0': 'NPC Nameplate Frame',
    'Game,6,50331673': 'NPC Nameplate Frame',
    'Game,6,50331673,0': 'NPC Nameplate Frame',
    'AgentCommander0,0': 'Hero 1 Window Fight Button',
    'AgentCommander0,1': 'Hero 1 Window Guard Button',
    'AgentCommander0,2': 'Hero 1 Window Avoid Button',
    'AgentCommander0,3': 'Hero 1 Window Avatar Frame',
    'AgentCommander0,3,0': 'Hero 1 Window Avatar Frame Content',
    'AgentCommander0,3,1': 'Hero 1 Window Avatar Frame Content 1',
    'AgentCommander0,5': 'Hero 1 Window Skill Bar',
    'AgentCommander0,5,2': 'Hero 1 Window Skill 3',
    'AgentCommander0,5,3': 'Hero 1 Window Skill 4',
    'AgentCommander0,5,4': 'Hero 1 Window Skill 5',
    'AgentCommander0,5,5': 'Hero 1 Window Skill 6',
    'AgentCommander0,5,6': 'Hero 1 Window Skill 7',
    'AgentCommander0,5,0': 'Hero 1 Window Skill 1',
    'AgentCommander0,5,1': 'Hero 1 Window Skill 2',
    'AgentCommander0,5,7': 'Hero 1 Window Skill 8',
    'AgentCommander0,6': 'Hero 1 Window Energy Bar',
    'AgentCommander0,7': 'Hero 1 Window Health Bar',
    'AgentCommander0,8': 'Hero 1 Window Target Button',
    'AgentCommander0,4': 'Hero 1 Window Buff Frame',
    'AgentCommander1,0': 'Hero 2 Window Fight Button',
    'AgentCommander1,1': 'Hero 2 Window Guard Button',
    'AgentCommander1,2': 'Hero 2 Window Avoid Button',
    'AgentCommander1,3': 'Hero 2 WindowAvatar Frame',
    'AgentCommander1,4': 'Hero 2 Window Buff Frame',
    'AgentCommander1,5': 'Hero 2 Window Skill Bar',
    'AgentCommander1,6': 'Hero 2 Window Energy Bar',
    'AgentCommander1,7': 'Hero 2 Window Health Bar',
    'AgentCommander1,8': 'Hero 2 Window Target Button',
    'Game,6,50331651': 'NPC Nameplate Frame',
    'Game,6,50331680': 'NPC Nameplate Frame',
    'Game,6,50331679': 'NPC Nameplate Frame',
    'Game,6,50331678': 'NPC Nameplate Frame',
    'Game,6,50331677': 'NPC Nameplate Frame',
    'Game,6,50331653': 'NPC Nameplate Frame',
    'Game,6,50331672': 'NPC Nameplate Frame',
    'Game,6,50331670': 'NPC Nameplate Frame',
    'Game,6,50331669': 'NPC Nameplate Frame',
    'Game,6,50331660': 'NPC Nameplate Frame',
    'Game,6,50331658': 'NPC Nameplate Frame',
    'Game,6,50331657': 'NPC Nameplate Frame',
    'Game,6,50331656': 'NPC Nameplate Frame',
    'Game,6,50331655': 'NPC Nameplate Frame',
    'Game,6,50331654': 'NPC Nameplate Frame',
    'Game,6,50331671': 'NPC Nameplate Frame',
    'Game,6,50331661': 'NPC Nameplate Frame',
    'Game,6,50331662': 'NPC Nameplate Frame',
    'Game,6,50331684': 'NPC Nameplate Frame',
    'Game,6,50331681': 'NPC Nameplate Frame',
    'Game,6,50331682': 'NPC Nameplate Frame',
    'Game,6,50331683': 'NPC Nameplate Frame',
    'Game,6,50331652': 'NPC Nameplate Frame',
    'Game,6,50331649': 'NPC Nameplate Frame',
    'Game,6,117': 'Floating Buttons.Log Out',
    'Game,6,50331650': 'NPC Nameplate Frame',
    'Game,6,50331656,0': '',
    'Game,6,50331685': 'NPC Nameplate Frame',
    'Game,6,50331663': 'NPC Nameplate Frame',
    'Game,6,50331665': 'NPC Nameplate Frame',
    'Game,6,50331682,0': 'NPC Nameplate Frame',
    'Game,6,50331659': 'NPC Nameplate Frame',
    'AgentCommander3,1': 'Hero 4 Window Guard Button',
    'AgentCommander3,0': 'Hero 4 Window Fight Button',
    'AgentCommander3,8': 'Hero 4 Window Target Button',
    'AgentCommander3,2': 'Hero 4 Window Avoid Button',
    'AgentCommander3,4': 'Hero 4 Window Buff Frame',
    'AgentCommander3,7': 'Hero 4 Window Health Bar',
    'AgentCommander3,5': 'Hero 4 Window Skill Bar',
    'AgentCommander3,3': 'Hero 4 Window Avatar Frame',
    'AgentCommander3,6': 'Hero 4 Window Energy Bar',
    'AgentCommander3,5,1': 'Hero 4 Window Skill 2',
    'AgentCommander3,5,3': 'Hero 4 Window Skill 4',
    'AgentCommander3,5,2': 'Hero 4 Window Skill 3',
    'AgentCommander3,5,0': 'Hero 4 Window Skill 1',
    'AgentCommander3,5,4': 'Hero 4 Window Skill 5',
    'AgentCommander3,5,5': 'Hero 4 Window Skill 6',
    'AgentCommander3,5,6': 'Hero 4 Window Skill 7',
    'AgentCommander3,5,7': 'Hero 4 Window Skill 8',
    'AgentCommander2,0': 'Hero 3 Window Fight Button',
    'AgentCommander2,2': 'Hero 3 Window Avoid Button',
    'AgentCommander2,1': 'Hero 3 Window Guard Button',
    'AgentCommander2,8': 'Hero 3 Window Target Button',
    'AgentCommander2,4': 'Hero 3 Window Buff Frame',
    'AgentCommander2,3': 'Hero 3 Window Avatar Frame',
    'AgentCommander2,6': 'Hero 3 Window Energy Bar',
    'AgentCommander2,7': 'Hero 3 Window Health Bar',
    'AgentCommander2,5': 'Hero 3 Window Skill Bar',
    'AgentCommander2,5,3': 'Hero 3 Window Skill 4',
    'AgentCommander2,5,5': 'Hero 3 Window Skill 6',
    'AgentCommander2,5,2': 'Hero 3 Window Skill 3',
    'AgentCommander2,5,6': 'Hero 3 Window Skill 7',
    'AgentCommander2,5,0': 'Hero 3 Window Skill 1',
    'AgentCommander2,5,7': 'Hero 3 Window Skill 8',
    'AgentCommander2,5,4': 'Hero 3 Window Skill 5',
    'AgentCommander2,5,1': 'Hero 3 Window Skill 2',
    'AgentCommander1,5,7': 'Hero 2 Window Skill 8',
    'AgentCommander1,5,0': 'Hero 2 Window Skill 1',
    'AgentCommander1,5,1': 'Hero 2 Window Skill 2',
    'AgentCommander1,5,6': 'Hero 2 Window Skill 7',
    'AgentCommander1,5,3': 'Hero 2 Window Skill 4',
    'AgentCommander1,5,4': 'Hero 2 Window Skill 5',
    'AgentCommander1,5,2': 'Hero 2 Window Skill 3',
    'AgentCommander1,5,5': 'Hero 2 Window Skill 6',
    'AgentCommander6,7': 'Hero 7 Window Health Bar',
    'AgentCommander6,0': 'Hero 7 Window Fight Button',
    'AgentCommander6,1': 'Hero 7 Window Guard Button',
    'AgentCommander6,8': 'Hero 7 Window Target Button',
    'AgentCommander6,2': 'Hero 7 Window Avoid Button',
    'AgentCommander6,3': 'Hero 7 Window Avatar Frame',
    'AgentCommander6,5': 'Hero 7 Window Skill Bar',
    'AgentCommander6,5,4': 'Hero 7 Window Skill 5',
    'AgentCommander6,5,6': 'Hero 7 Window Skill 7',
    'AgentCommander6,5,5': 'Hero 7 Window Skill 6',
    'AgentCommander6,5,1': 'Hero 7 Window Skill 2',
    'AgentCommander6,5,3': 'Hero 7 Window Skill 4',
    'AgentCommander6,5,2': 'Hero 7 Window Skill 3',
    'AgentCommander6,5,7': 'Hero 7 Window Skill 8',
    'AgentCommander6,5,0': 'Hero 7 Window Skill 1',
    'AgentCommander6,6': 'Hero 7 Window Energy Bar',
    'AgentCommander6,4': 'Hero 7 Window Buff Frame',
    'AgentCommander5,1': 'Hero 6 Window Guard Button',
    'AgentCommander5,8': 'Hero 6 Window Target Button',
    'AgentCommander5,0': 'Hero 6 Window Fight Button',
    'AgentCommander5,2': 'Hero 6 Window Avoid Button',
    'AgentCommander5,7': 'Hero 6 Window Health Bar',
    'AgentCommander5,3': 'Hero 6 Window Avatar Frame',
    'AgentCommander5,4': 'Hero 6 Window Buff Frame',
    'AgentCommander5,6': 'Hero 6 Window Energy Bar',
    'AgentCommander5,5': 'Hero 6 Window Skill Bar',
    'AgentCommander5,5,3': 'Hero 6 Window Skill 4',
    'AgentCommander5,5,6': 'Hero 6 Window Skill 7',
    'AgentCommander5,5,2': 'Hero 6 Window Skill 3',
    'AgentCommander5,5,4': 'Hero 6 Window Skill 5',
    'AgentCommander5,5,1': 'Hero 6 Window Skill 2',
    'AgentCommander5,5,5': 'Hero 6 Window Skill 6',
    'AgentCommander5,5,0': 'Hero 6 Window Skill 1',
    'AgentCommander5,5,7': 'Hero 6 Window Skill 8',
    'AgentCommander4,5': 'Hero 5 Window Skill Bar',
    'AgentCommander4,5,2': 'Hero 5 Window Skill 3',
    'AgentCommander4,5,3': 'Hero 5 Window Skill 4',
    'AgentCommander4,5,1': 'Hero 5 Window Skill 2',
    'AgentCommander4,5,0': 'Hero 5 Window Skill 1',
    'AgentCommander4,5,5': 'Hero 5 Window Skill 6',
    'AgentCommander4,5,4': 'Hero 5 Window Skill 5',
    'AgentCommander4,5,6': 'Hero 5 Window Skill 7',
    'AgentCommander4,5,7': 'Hero 5 Window Skill 8',
    'AgentCommander4,3': 'Hero 5 Window Avatar Frame',
    'AgentCommander4,7': 'Hero 5 Window Health Bar',
    'AgentCommander4,8': 'Hero 5 Window Target Button',
    'AgentCommander4,6': 'Hero 5 Window Energy Bar',
    'AgentCommander4,4': 'Hero 5 Window Buff Frame',
    'AgentCommander4,1': 'Hero 5 Window Guard Button',
    'AgentCommander4,2': 'Hero 5 Window Avoid Button',
    'AgentCommander4,0': 'Hero 5 Window Fight Button',
    'Attributes,4': 'Hero Window.Class',
    'Attributes,3': 'Hero Window.CharacterName',
    'Attributes,2': 'Hero Window.Tabs',
    'Attributes,2,4294967295': 'Hero Window.Tabs.AccountTab',
    'Attributes,2,4294967294': 'Hero Window.Tabs.FactionTab',
    'Attributes,2,4294967293': 'Hero Window.Tabs.TitlesTab',
    'Attributes,1': 'Hero Window.CharacterAvatar',
    'Attributes,0': 'Hero Window.Info',
    'Attributes,0,1': 'Hero Window.Info.Level',
    'Attributes,0,2': 'Hero Window.Info.SkillPoints',
    'Attributes,0,0': 'Hero Window.Info.XPBar',
    'Attributes,2,1': 'Hero Window.Tabs.FactionTab.Content',
    'Attributes,2,1,0': 'Hero Window.Tabs.FactionTab.ContentInner',
    'Attributes,2,1,0,0': 'Hero Window.Tabs.FactionTab.ContentInner.Factions',
    'Attributes,2,1,0,0,0': 'Hero Window.Tabs.FactionTab.ContentInner.Factions.Bars',
    'Attributes,2,1,0,0,0,2': 'Hero Window.Tabs.FactionTab.ContentInner.Factions.Bars.Balthazar',
    'Attributes,2,1,0,0,0,0': 'Hero Window.Tabs.FactionTab.ContentInner.Factions.Bars.Kurzick',
    'Attributes,2,1,0,0,0,3': 'Hero Window.Tabs.FactionTab.ContentInner.Factions.Bars.Imperial',
    'Attributes,2,1,0,0,0,1': 'Hero Window.Tabs.FactionTab.ContentInner.Factions.Bars.Luxon',
    'Attributes,2,0': 'Hero Window.Tabs.AccountTab.Content',
    'Attributes,2,0,0': 'Hero Window.Tabs.AccountTab.ContentInner',
    'Attributes,2,0,0,0,1': 'Hero Window.Tabs.AccountTab.ContentInner.Account.Name',
    'Attributes,2,0,0,0,2': 'Hero Window.Tabs.AccountTab.ContentInner.Account.TournamentInfo',
    'Attributes,2,0,0,0,4': 'Hero Window.Tabs.AccountTab.ContentInner.Account.TournamentData',
    'Attributes,2,0,0,0,4,1': 'Hero Window.Tabs.AccountTab.ContentInner.Account.TournamentData.RewardPoints',
    'Attributes,2,0,0,0,4,0': 'Hero Window.Tabs.AccountTab.ContentInner.Account.TournamentData.TournamentLabel',
    'Attributes,2,0,0,0': 'Hero Window.Tabs.AccountTab.ContentInner.Account',
    'Attributes,2,2': 'Hero Window.Tabs.TitlesTab.Content',
    'Attributes,2,2,0': 'Hero Window.Tabs.TitlesTab.ContentInner',
    'Attributes,2,2,0,3': 'Hero Window.Tabs.TitlesTab.ContentInner.ScrollBar',
    'Attributes,2,2,0,0': 'Hero Window.Tabs.TitlesTab.ContentInner.Titles',
    'Attributes,2,2,0,0,0': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea',
    'Attributes,2,2,0,0,0,24': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.TyrianEliteSkillHunter',
    'Attributes,2,2,0,0,0,2': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.CanthaExplorationTitleTrack',
    'Attributes,2,2,0,0,0,5': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.KurzickSupporter',
    'Attributes,2,2,0,0,0,25': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.TyrianVanquisher',
    'Attributes,2,2,0,0,0,7': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.Drunkard',
    'Attributes,2,2,0,0,0,33': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.LegendaryVanquisher',
    'Attributes,2,2,0,0,0,41': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.Norn',
    'Attributes,2,2,0,0,0,17': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.Sunspear',
    'Attributes,2,2,0,0,0,19': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.ProtectorofElona',
    'Attributes,2,2,0,0,0,10': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.GWAMM',
    'Attributes,2,2,0,0,0,28': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.TyrianEliteSkillHunter',
    'Attributes,2,2,0,0,0,15': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.Lucky',
    'Attributes,2,2,0,0,0,46': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.Wisdom',
    'Attributes,2,2,0,0,0,16': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.Unlucky',
    'Attributes,2,2,0,0,0,42': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.EOTNMastery',
    'Attributes,2,2,0,0,0,23': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.Gamer',
    'Attributes,2,2,0,0,0,13': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.ProtectorofTyria',
    'Attributes,2,2,0,0,0,34': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.SweetTooth',
    'Attributes,2,2,0,0,0,43': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.PartyAnimal',
    'Attributes,2,2,0,0,0,21': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.LDOA',
    'Attributes,2,2,0,0,0,14': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.ProtectorofCantha',
    'Attributes,2,2,0,0,0,39': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.Deldrimor',
    'Attributes,2,2,0,0,0,20': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.Lightbringer',
    'Attributes,2,2,0,0,0,35': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.GuardianofTyria',
    'Attributes,2,2,0,0,0,31': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.LegendaryGuardian',
    'Attributes,2,2,0,0,0,18': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.ElonaExploration',
    'Attributes,2,2,0,0,0,38': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.Asura',
    'Attributes,2,2,0,0,0,45': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.TreasureHunter',
    'Attributes,2,2,0,0,0,1': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.TyrianExploration',
    'Attributes,2,2,0,0,0,44': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.Zaishen',
    'Attributes,2,2,0,0,0,40': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.EbonVanguard',
    'Attributes,2,2,0,0,0,27': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.CanthanVanquisher',
    'Attributes,2,2,0,0,0,9': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.Survivor',
    'Attributes,2,2,0,0,0,26': 'Hero Window.Tabs.TitlesTab.ContentInner.TitlesArea.CanthanEliteSkillHunter',
    'Inventory,8': 'Inventory Window.DividerBelowHeroes',
    'Inventory,9,16777231': 'Inventory Window.Party Portraits.Portrait2',
    'Inventory,9,16777235': 'Inventory Window.Party Portraits.Portrait6',
    'Inventory,9,16777232': 'Inventory Window.Party Portraits.Portrait3',
    'Inventory,9,16777230': 'Inventory Window.Party Portraits.Portrait1',
    'Inventory,9,16777233': 'Inventory Window.Party Portraits.Portrait4',
    'Inventory,9,16777234': 'Inventory Window.Party Portraits.Portrait5',
    'Inventory,9,16777237': 'Inventory Window.Party Portraits.Portrait8',
    'Inventory,9,16777236': 'Inventory Window.Party Portraits.Portrait7',
    'Doll': 'Character_Preview_Frame',
    'Game,6,50331666': 'NPC Nameplate Frame',
    'Game,6,50331667': 'NPC Nameplate Frame',
    'Game,6,50331668': 'NPC Nameplate Frame',
    'Game,6,50331709': 'NPC Nameplate Frame',
    'Game,6,50331711': 'NPC Nameplate Frame',
    'Game,6,50331790': 'NPC Nameplate Frame',
    'Game,6,50331793': 'NPC Nameplate Frame',
    'Game,6,50331792': 'NPC Nameplate Frame',
    'Game,6,50331700': 'NPC Nameplate Frame',
    'Game,6,50331703': 'NPC Nameplate Frame',
    'Game,6,50331797': 'NPC Nameplate Frame',
    'Game,6,50331690': 'NPC Nameplate Frame',
    'Game,6,50331701': 'NPC Nameplate Frame',
    'Game,6,50331798': 'NPC Nameplate Frame',
    'Game,6,50331802': 'NPC Nameplate Frame',
    'Game,6,50331708': 'NPC Nameplate Frame',
    'Game,6,50331786': 'NPC Nameplate Frame',
    'Game,6,50331799': 'NPC Nameplate Frame',
    'Game,6,50331789': 'NPC Nameplate Frame',
    'Game,6,50331800': 'NPC Nameplate Frame',
    'Game,6,50331706': 'NPC Nameplate Frame',
    'Game,6,50331693': 'NPC Nameplate Frame',
    'Game,6,50331691': 'NPC Nameplate Frame',
    'Game,6,50331692': 'NPC Nameplate Frame',
    'Game,6,50331785': 'NPC Nameplate Frame',
    'Game,6,50331788': 'NPC Nameplate Frame',
    'Game,6,50331697': 'NPC Nameplate Frame',
    'Game,6,50331791': 'NPC Nameplate Frame',
    'Game,6,50331695': 'NPC Nameplate Frame',
    'Game,6,50331702': 'NPC Nameplate Frame',
    'Game,6,50331795': 'NPC Nameplate Frame',
    'Game,6,50331794': 'NPC Nameplate Frame',
    'Game,6,50331704': 'NPC Nameplate Frame',
    'Game,6,50331699': 'NPC Nameplate Frame',
    'Game,6,50331803': 'NPC Nameplate Frame',
    'Game,6,50331801': 'NPC Nameplate Frame',
    'Game,6,50331796': 'NPC Nameplate Frame',
    'Game,6,50331696': 'NPC Nameplate Frame',
    'Game,6,50331698': 'NPC Nameplate Frame',
    'Game,6,50331804': 'NPC Nameplate Frame',
    'Game,6,50331787': 'NPC Nameplate Frame',
    'Game,6,50331707': 'NPC Nameplate Frame',
    'Game,6,50331710': 'NPC Nameplate Frame',
    'Game,6,50331705': 'NPC Nameplate Frame',
    'Game,6,50331694': 'NPC Nameplate Frame',
    'Game,6,50331823': 'NPC Nameplate Frame',
    'Game,6,50331822': 'NPC Nameplate Frame',
    'Game,6,50331821': 'NPC Nameplate Frame',
    'Game,6,50331828': 'NPC Nameplate Frame',
    'Game,6,50331819': 'NPC Nameplate Frame',
    'Game,6,50331825': 'NPC Nameplate Frame',
    'Game,6,50331829': 'NPC Nameplate Frame',
    'Game,6,50331832': 'NPC Nameplate Frame',
    'Game,6,50331820': 'NPC Nameplate Frame',
    'Game,6,50331689': 'NPC Nameplate Frame',
    'Game,6,50331688': 'NPC Nameplate Frame',
    'Game,5,1': 'Character_Select_Frame',
    'Play': 'Character_Select_Frame.Play_Button',
    'PlayNoChar': 'Character_Select_Frame.Play_Button_Greyed_Out',
    'CharCreate': 'Character_Select_Frame.Create_Button',
    'CharCreateNoChar': 'Character_Select_Frame.Create_Button_Greyed_Out',
    'CharDelete': 'Character_Select_Frame.Delete_Button',
    'Game,5,1,15': 'Character_Select_Frame.Delete_Button.Delete_Character_Frame',
    'Game,5,1,15,3': 'Character_Select_Frame.Delete_Button.Delete_Character_Frame.Cancel_Button',
    'Game,5,1,15,0': 'Character_Select_Frame.Delete_Button.Delete_Character_Frame.TEXT',
    'Game,5,1,15,1': 'Character_Select_Frame.Delete_Button.Delete_Character_Frame.Name_Input',
    'Game,5,1,15,2': 'Character_Select_Frame.Delete_Button.Delete_Character_Frame.Delete_Button',
    'Logout': 'Character_Select_Frame.Log_Out_Button',
    'EditAcct': 'Character_Select_Frame.Edit_Account_Button',
    'StatusOverride': 'Character_Select_Frame.Status_dropdown',
    'Selector': 'Character_Select_Frame.Character_Frame',
    'Sort': 'Character_Select_Frame.Sort_Frame',
    'Sort,0': 'Character_Select_Frame.Sort_Frame.Sort_dropdown',
    'Sort,0,0': 'Character_Select_Frame.Sort_Frame.Sort_dropdown.Dropdown_Window',
    'Sort,1': 'Character_Select_Frame.Sort_Frame.TEXT',
    'Purchase': 'Character_Select_Frame.Mercenary_Slot_Ad',
    'Purchase,1': 'Character_Select_Frame.Mercenary_Slot_Ad.Small_TEXT',
    'Purchase,2': 'Character_Select_Frame.Mercenary_Slot_Ad.large_TEXT',
    'Purchase,0': 'Character_Select_Frame.Mercenary_Slot_Ad.Enter_Store_Button',
    'SlotCount': 'Character_Select_Frame.Character_Slots_in_Use_Frame',
    'info': 'Character_Select_Frame.Character_Info_Frame',
    'info,3': 'Character_Select_Frame.Character_Info_Frame.Character_Name.TEXT',
    'info,4': 'Character_Select_Frame.Character_Info_Frame.Character_Class.TEXT',
    'info,6': 'Character_Select_Frame.Character_Info_Frame.Character_Type.TEXT',
    'info,0': 'Character_Select_Frame.Character_Info_Frame.Character_Campaign.TEXT',
    'info,1': 'Character_Select_Frame.Character_Info_Frame.Character_Level.TEXT',
    'info,2': 'Character_Select_Frame.Character_Info_Frame.Character_Location.TEXT',
    'HideUi': 'Login_Screen.Hide_UI_Checkbox',
    'OptionsBtn': 'Login_Screen.Options_Button',
    'Back': 'Character_Create_Character_Type_Frame.Back_Button',
    'Next': 'Character_Create_Character_Type_Frame.Next_Button',
    'Title': 'Character_Create_Character_Type_Frame.Choose_Your_Character_Type_Text',
    'StateTitle': 'Character_Create_Character_Frame.Top_TEXT',
    'Name': 'Character_Create_Character_Name_Frame.Characer_Name_Frame',
    'Name,0': 'Character_Creation.Name_Window.Character_Name_Window.Title_Text',
    'Name,1,1': 'Character_Create_Character_Name_Frame.Characer_Name_Frame.Character_Name_Input',
    'StateCreate': 'Character_Creation.Name_Window.Create_Button',
    'Selector,0': 'Character_Select.Character_Frame.Child',
    'Chapter': 'Character_Create_Character_Campaign_Frame.Select_Campaign_Slider_Frame',
    'State': 'Create_Character_Bottom_Frame',
    'State,0': 'Create_Character.Bottom_Button_Frame.Campaign_Tab',
    'State,1': 'Create_Character.Bottom_Button_Frame.Profession_Tab',
    'State,1,1': 'Create_Character.Bottom_Button_Frame.Profession_Tab.TEXT',
    'State,0,1': 'Create_Character.Bottom_Button_Frame.Campaign_Tab.TEXT',
    'State,2': 'Create_Character.Bottom_Button_Frame.Sex_Tab',
    'State,2,1': 'Create_Character.Bottom_Button_Frame.Sex_Tab.TEXT',
    'State,3': 'Create_Character.Bottom_Button_Frame.Appearance_Tab',
    'State,3,1': 'Create_Character.Bottom_Button_Frame.Appearance_Tab.TEXT',
    'State,4': 'Create_Character.Bottom_Button_Frame.Body_Tab',
    'State,4,1': 'Create_Character.Bottom_Button_Frame.Body_Tab.TEXT',
    'State,5': 'Create_Character.Bottom_Button_Frame.Name_Tab',
    'State,5,1': 'Create_Character.Bottom_Button_Frame.Name_Tab.TEXT',
    'Game': 'Screen_Frame',
    'Game,5': 'Screen_Frame.Child',
    'Game,5,2': 'Character_Create_Character_Type_Frame',
    'Game,3': 'Character_Create_Character_Frame',
    'StateCancel': 'Character_Create_Character_Campaign_Frame.Back_Button',
    'StateNext': 'Character_Create_Character_Frame.Next_Button',
    'Chapter,0': 'Character_Create_Character_Campaign_Frame.Select_Campaign_Slider_Frame.Child',
    'StatePrev': 'Character_Create_Character_Frame.Back_Button',
    'Profession,1': 'Character_Create_Character_Profession_Frame.Bottom_TEXT',
    'Profession': 'Character_Create_Character_Profession_Frame',
    'Profession,0': 'Character_Create_Character_Profession_Frame.Child',
    'Sex': 'Character_Create_Character_Sex_Frame',
    'Sex,0': 'Character_Create_Character_Sex_Frame.Child',
    'Download': 'Frame_Spacer',
    'Appearance': 'Character_Create_Character_Appearance_Frame',
    'SkinColor': 'Character_Create_Character_Appearance_Frame.Skin_Color_Frame',
    'HairStyle': 'Character_Create_Character_Appearance_Frame.Hair_Style_Frame',
    'HairColor': 'Character_Create_Character_Appearance_Frame.Hair_Color_Frame',
    'FaceType': 'Character_Create_Character_Appearance_Frame.Face_Frame',
    'Face1': 'Character_Create_Character_Appearance_Frame.Options.Option_1',
    'Face2': 'Character_Create_Character_Appearance_Frame.Options.Option_2',
    'Face3': 'Character_Create_Character_Appearance_Frame.Options.Option_3',
    'Face4': 'Character_Create_Character_Appearance_Frame.Options.Option_4',
    'Face5': 'Character_Create_Character_Appearance_Frame.Options.Option_5',
    'Face6': 'Character_Create_Character_Appearance_Frame.Options.Option_6',
    'Face7': 'Character_Create_Character_Appearance_Frame.Options.Option_7',
    'Face8': 'Character_Create_Character_Appearance_Frame.Options.Option_8',
    'Label': 'Character_Create_Character_Frame.TEXT',
    'Face9': 'Character_Create_Character_Appearance_Frame.Options.Option_9',
    'Face10': 'Character_Create_Character_Appearance_Frame.Options.Option_10',
    'Face11': 'Character_Create_Character_Appearance_Frame.Options.Option_11',
    'Face12': 'Character_Create_Character_Appearance_Frame.Options.Option_12',
    'Face13': 'Character_Create_Character_Appearance_Frame.Options.Option_13',
    'Face14': 'Character_Create_Character_Appearance_Frame.Options.Option_14',
    'Face15': 'Character_Create_Character_Appearance_Frame.Options.Option_15',
    'Face16': 'Character_Create_Character_Appearance_Frame.Options.Option_16',
    'Selection': 'Character_Create_Character_Appearance_Frame.Options.Selected_Option',
    'BodyScale': 'Character_Create_Character_Body_Frame.Body_Scale_Frame',
    'SliderMarker': 'Character_Create_Character_Body_Frame.Body_Scale_Frame.Ruler',
    'ScaleSlider': 'Character_Create_Character_Body_Frame.Body_Scale_Frame.Arrow',
    'ItemColor': 'Character_Create_Character_Body_Frame.Armor_Frame',
    'HeadLabel': 'Character_Create_Character_Body_Frame.Armor_Frame.Head_TEXT',
    'TorsoLabel': 'Character_Create_Character_Body_Frame.Armor_Frame.Chest_TEXT',
    'HandsLabel': 'Character_Create_Character_Body_Frame.Armor_Frame.Hands_TEXT',
    'LegsLabel': 'Character_Create_Character_Body_Frame.Armor_Frame.Legs_TEXT',
    'FeetLabel': 'Character_Create_Character_Body_Frame.Armor_Frame.Feet_TEXT',
    'Head': 'Character_Create_Character_Body_Frame.Armor_Frame.Head_Frame',
    'ItemIcon': 'Character_Create_Character_Body_Frame.Armor_Frame.Armor_Icon',
    'Colors': 'Character_Create_Character_Body_Frame.Armor_Frame.Head_Frame.Armor_Dye',
    'Torso': 'Character_Create_Character_Body_Frame.Armor_Frame.Chest_Frame',
    'Legs': 'Character_Create_Character_Body_Frame.Armor_Frame.Legs_Frame',
    'Hands': 'Character_Create_Character_Body_Frame.Armor_Frame.Hands_Frame',
    'Feet': 'Character_Create_Character_Body_Frame.Armor_Frame.Feet_Frame',
    'ShowHead': 'Character_Create_Character_Body_Frame.Armor_Frame.Head_Frame.Show_Checkbox',
    'Colors,0': 'Character_Create_Character_Body_Frame.Armor_Frame.Grey_Dye',
    'Colors,1': 'Character_Create_Character_Body_Frame.Armor_Frame.Blue_Dye',
    'Colors,2': 'Character_Create_Character_Body_Frame.Armor_Frame.Green_Dye',
    'Colors,3': 'Character_Create_Character_Body_Frame.Armor_Frame.Purple_Dye',
    'Colors,4': 'Character_Create_Character_Body_Frame.Armor_Frame.Red_Dye',
    'Colors,5': 'Character_Create_Character_Body_Frame.Armor_Frame.Yellow_Dye',
    'Colors,6': 'Character_Create_Character_Body_Frame.Armor_Frame.Brown_Dye',
    'Colors,7': 'Character_Create_Character_Body_Frame.Armor_Frame.Orange_Dye',
    'CameraHelp': 'Character_Create_Character_Name_Frame.Mouse_Instructions_Frame',
    'TxtHelp': 'Character_Create_Character_Name_Frame.Mouse_Instructions_Frame.TEXT',
    'ImgHelp': 'Character_Create_Character_Name_Frame.Mouse_Instructions_Frame.ICONS',
    'Name,1': 'Character_Create_Character_Name_Frame.Characer_Name_Frame.Child',
    'Name,1,2': 'Character_Create_Character_Name_Frame.Characer_Name_Frame.Middle_TEXT',
    'Name,1,4': 'Character_Create_Character_Name_Frame.Characer_Name_Frame.under_input_TEXT',
    'Name,1,5': 'Character_Create_Character_Name_Frame.Characer_Name_Frame.Character_Name_Check1',
    'Name,1,6': 'Character_Create_Character_Name_Frame.Characer_Name_Frame.Character_Name_Check2',
    'Name,1,9': 'Character_Create_Character_Name_Frame.Characer_Name_Frame.Character_Name_Check3',
    'Name,1,7': 'Character_Create_Character_Name_Frame.Characer_Name_Frame.Character_Name_Check4',
    'Quest,3,3': 'Quest Log Window.ScrollBar',
    'PetCommanderPlayer': 'Pet Control',
    'Party,0,0,0,8': 'Party Formation.Frame.Explorable.Pets Header',
    'Party,0,0,0,8,0': 'Party Formation.Frame.Explorable.Pets Header.Expand',
    'Party,0,0,0,8,1': 'Party Formation.Frame.Explorable.Pets Header.Title',
    'StartMenuBar,0': 'menu button_menu',
    'StartMenuBar,0,1': 'menu button hero menu',
    'StartMenuBar,0,1608675812': 'seperator',
    'Options,1': 'Options Window Inner Frame',
    'Options,1,4294967291': 'Interface Options Tab',
    'Options,1,0': 'General Options Tab Internal',
    'Options,1,1': 'Graphics Options Tab Internal',
    'Options,1,4294967295': 'General Options Tab',
    'Options,1,4294967294': 'Graphics Options Tab',
    'Options,1,4': 'Interface Options Tab Internal',
    'Options,1,4294967293': 'Sound Options Tab',
    'Options,1,4294967292': 'Control Options Tab',
    'Options,1,3': 'Control Options Tab Internal',
    'Options,1,2': 'Sound Options Tab Internal',
    'Options,0': 'Options Window GW Version',
    'Game,10': 'did_not_cleaning_disconnect_popup_charselect',
    'BtnYes': 'did_not_cleaning_disconnect_popup_charselect_YES_BUTTON',
    'BtnNo': 'did_not_cleaning_disconnect_popup_charselect_NO_BUTTON',
    'TxtMessage': 'did_not_cleaning_disconnect_popup_charselect_TEXT_FRAME',
    'ImgIcon': 'did_not_cleaning_disconnect_popup_charselect_QUESTION_MARK',
    'Game,17,0': 'guild_wars_was_unable_to_complete_the_operation_popup_charselect',
    'Game,17,0,0': 'guild_wars_was_unable_to_complete_the_operation_popup_charselect_EXCLIMATION_MARK',
    'Game,17,0,5': 'guild_wars_was_unable_to_complete_the_operation_popup_charselect_OK_BUTTON',
    'Game,17,0,1': 'guild_wars_was_unable_to_complete_the_operation_popup_charselect_TEXT_FRAME',
    'InvAggregate,0': 'Inventory Bags Window.Content',
    'MapWindow': 'Mission Map',
    'Vendor': 'Merchant',
    'Vendor,0,0,6': 'Collector.Exchange',
    'BtnBuy': 'Merchant Buy Button',
    'DlgSkillPlace': 'Equip Skill Window',
    'BtnEquip': 'Equip Skill Window.Equip Now',
    'Game,12,4': 'No Leave your party button',
    'Game,12,6': 'Yes Leave your party Button',
    'Game,12': 'Leave your party Dialog',
    'Game,6,1,0': 'Skip Cutscene Button',
    'Options,1,4294967290': 'Gamepad Options Tab',
    'Party,1,8,0,0,0,0': 'PartyMembersParent',
    'Party,1,8,0,0,0,0,7': 'PartyMember7',
    'Party,1,8,0,0,0,0,1,1': 'PartyReadyToggle',
    'Party,0,0,0,0': 'PartyMembersParentExplorable',
    'Game,6,111,4': 'SalvageWithLesserKit_Cancel',
    'Game,6,111,6': 'SalvageWithLesserKit_Confirm',
    'Game,6,111': 'LesserSalvageWindow',
    'Game,6,112': 'Expert Salvage - Unidentified Item',
    'Game,6,112,6': 'Expert Salvage - Unidentified Item CONFIRM',
    'Game,6,112,4': 'Expert Salvage - Unidentified Item CANCEL',
    'Salvage,0': 'SalvageOptionsWindowConfirmMaterialsWindow',
    'Salvage,0,4': 'SalvageOptionsWindowConfirmMaterialsWindow CANCEL',
    'Salvage,0,6': 'SalvageOptionsWindowConfirmMaterialsWindow CONFIRM',
    'InvUpgrade': 'Upgrade Window',
    'InvUpgrade,0': 'Upgrade Window Cancel',
    'InvUpgrade,1': 'Upgrade Window Confirm',
    'InvAccount,5': 'Xunlai Window.Deposit All Materials',
    'InvAccount,2': 'Xunlai Window.Gold Frame',
    'InvAccount,2,3': 'Xunlai Window.PlatinumValue',
    'InvAccount,2,2': 'Xunlai Window.GoldValue',
    'InvAccount,2,1': 'Xunlai Window.PlatinumIcon',
    'InvAccount,2,0': 'Xunlai Window.GoldIcon',
    'IdentifyAll': 'Inventory.IdentifyAll',
    'Inventory,0': 'Inventory.Backpack',
    'Inventory,0,2': 'Inventory.Backpack.Slot_1',
    'Inventory,0,3': 'Inventory.Backpack.Slot_2',
    'Inventory,1': 'Inventory.BeltPouch',
    'Inventory,1,2': 'Inventory.BeltPouch.Slot_1',
    'Inventory,1,3': 'Inventory.BeltPouch.Slot_2',
    'Inventory,2': 'Inventory.Bag1',
    'Inventory,2,3': 'Inventory.Bag1.Slot_2',
    'Inventory,2,2': 'Inventory.Bag1.Slot_1',
    'Inventory,3': 'Inventory.Bag2',
    'Inventory,3,2': 'Inventory.Bag2.Slot_1',
    'Inventory,3,3': 'Inventory.Bag2.Slot_2',
    'Inventory,4': 'Inventory.EquipmentPack',
    'Inventory,4,2': 'Inventory.EquipmentPack.Slot_1',
    'Inventory,4,3': 'Inventory.EquipmentPack.Slot_2',
    'Inventory,4,16': 'Inventory.EquipmentPack.Slot_15',
    'Inventory,4,21': 'Inventory.EquipmentPack.Slot_20',
    'Inventory,1,11': 'Inventory.BeltPouch.Slot_10',
    'Vendor,0,0,7': 'Collector.Goodbye',
    'Vendor,0,0,4,0,0': 'Collector.ItemContainer',
    'Vendor,0,0,4,0,0,489': 'Collector.ItemContainer.Item1',
    'Vendor,0,0,4,0,0,490': 'Collector.ItemContainer.Item2',
    'BtnCustomize': 'Merchant.CustomizeWeaponButton',
}
