"""The item catalog -- shipped reference data.

**Package data**: versioned with the code, never written at runtime. It is deliberately NOT in the
JSON store -- `.gitignore` excludes `json/**` entirely, so a catalog kept there is absent from a fresh
clone, and `JsonFactory` seeds from Defaults only when a document does not already exist, so an empty
runtime copy can never self-heal. That failure emptied the catalog twice.

**Vocabulary**: a **category** contains **groups**. (The legacy data called these `group` and
`subgroup`.) Only meaningful distinctions are groups -- Materials -> Common / Rare, Keys -> the four
campaigns. **Trophies has no groups**: its A...W split was alphabetical indexing, which is a rendering
concern and is banded at draw time instead.

Every `model_id` here is real. 373 came from the `ModelID` enum; 14 were recovered by name from the
bundled item metadata after their enum entries proved missing or held placeholder values (ids far
outside the valid range, e.g. `1236547896911`). The 16 that could not be resolved are in
:data:`UNRESOLVED` -- surfaced as defects, never shipped as rows that look functional but can never
match.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class CatalogEntry:
    """One shipped item. ``group`` is empty for categories that have no second level."""

    name: str
    model_id: int
    category: str
    group: str


@dataclass(frozen=True)
class UnresolvedEntry:
    """A real item whose model id is unknown to every bundled source. A visible defect."""

    name: str
    category: str


CATALOG: tuple[CatalogEntry, ...] = (
    CatalogEntry('Bottle Of Rice Wine', 15477, 'Alcohol', '1 Points'),
    CatalogEntry('Bottle Of Vabbian Wine', 19173, 'Alcohol', '1 Points'),
    CatalogEntry('Dwarven Ale', 5585, 'Alcohol', '1 Points'),
    CatalogEntry('Eggnog', 6375, 'Alcohol', '1 Points'),
    CatalogEntry('Hard Apple Cider', 28435, 'Alcohol', '1 Points'),
    CatalogEntry('Hunters Ale', 910, 'Alcohol', '1 Points'),
    CatalogEntry('Shamrock Ale', 22190, 'Alcohol', '1 Points'),
    CatalogEntry('Vial Of Absinthe', 6367, 'Alcohol', '1 Points'),
    CatalogEntry('Witchs Brew', 6049, 'Alcohol', '1 Points'),
    CatalogEntry('Zehtukas Jug', 19171, 'Alcohol', '1 Points'),
    CatalogEntry('Aged Dwarven Ale', 24593, 'Alcohol', '3 Points'),
    CatalogEntry('Bottle Of Grog', 30855, 'Alcohol', '3 Points'),
    CatalogEntry('Krytan Brandy', 35124, 'Alcohol', '3 Points'),
    CatalogEntry('Spiked Eggnog', 6366, 'Alcohol', '3 Points'),
    CatalogEntry('Battle Isle Iced Tea', 36682, 'Alcohol', '50 Points'),
    CatalogEntry('Fruitcake', 21492, 'Sweets', '1 Points'),
    CatalogEntry('Golden Egg', 22752, 'Sweets', '1 Points'),
    CatalogEntry('Sugary Blue Drink', 21812, 'Sweets', '1 Points'),
    CatalogEntry('Honeycomb', 26784, 'Sweets', '1 Points'),
    CatalogEntry('Slice Of Pumpkin Pie', 28436, 'Sweets', '1 Points'),
    CatalogEntry('Wintergreen Cc', 21488, 'Sweets', '1 Points'),
    CatalogEntry('Rainbow Cc', 21489, 'Sweets', '1 Points'),
    CatalogEntry('Peppermint Cc', 6370, 'Sweets', '2 Points'),
    CatalogEntry('Birthday Cupcake', 22269, 'Sweets', '2 Points'),
    CatalogEntry('Chocolate Bunny', 22644, 'Sweets', '2 Points'),
    CatalogEntry('Red Bean Cake', 15479, 'Sweets', '2 Points'),
    CatalogEntry('Creme Brulee', 15528, 'Sweets', '2 Points'),
    CatalogEntry('Delicious Cake', 36681, 'Sweets', '50 Points'),
    CatalogEntry('Bottle Rocket', 21809, 'Party', '1 Points'),
    CatalogEntry('Champagne Popper', 21810, 'Party', '1 Points'),
    CatalogEntry('Sparkler', 21813, 'Party', '1 Points'),
    CatalogEntry('Snowman Summoner', 6376, 'Party', '1 Points'),
    CatalogEntry('El Mischievious Tonic', 31021, 'Party', '2 Points'),
    CatalogEntry('El Yuletide Tonic', 29241, 'Party', '2 Points'),
    CatalogEntry('Party Beacon', 36683, 'Party', '50 Points'),
    CatalogEntry('Four Leaf Clover', 22191, 'Death Penalty Removal', 'Lucky Points'),
    CatalogEntry('Scroll Of Hunters Insight', 5976, 'Scrolls', 'Common XP Scrolls'),
    CatalogEntry('Scroll Of Rampagers Insight', 5975, 'Scrolls', 'Common XP Scrolls'),
    CatalogEntry('Scroll Of Adventurers Insight', 5853, 'Scrolls', 'Common XP Scrolls'),
    CatalogEntry('Scroll Of Heros Insight', 5594, 'Scrolls', 'Rare XP Scrolls'),
    CatalogEntry('Slayers Insight Scroll', 5611, 'Scrolls', 'Rare XP Scrolls'),
    CatalogEntry('Scroll Of Berserkers Insight', 5595, 'Scrolls', 'Rare XP Scrolls'),
    CatalogEntry('Passage Scroll Deep', 22279, 'Scrolls', 'Passage Scrolls'),
    CatalogEntry('Passage Scroll Fow', 22280, 'Scrolls', 'Passage Scrolls'),
    CatalogEntry('Passage Scroll Urgoz', 3256, 'Scrolls', 'Passage Scrolls'),
    CatalogEntry('Passage Scroll Uw', 3746, 'Scrolls', 'Passage Scrolls'),
    CatalogEntry('Assassin Tome', 21796, 'Tomes', 'Normal Tomes'),
    CatalogEntry('Dervish Tome', 21803, 'Tomes', 'Normal Tomes'),
    CatalogEntry('Elementalist Tome', 21799, 'Tomes', 'Normal Tomes'),
    CatalogEntry('Mesmer Tome', 21797, 'Tomes', 'Normal Tomes'),
    CatalogEntry('Monk Tome', 21800, 'Tomes', 'Normal Tomes'),
    CatalogEntry('Necromancer Tome', 21798, 'Tomes', 'Normal Tomes'),
    CatalogEntry('Paragon Tome', 21805, 'Tomes', 'Normal Tomes'),
    CatalogEntry('Ranger Tome', 21802, 'Tomes', 'Normal Tomes'),
    CatalogEntry('Ritualist Tome', 21804, 'Tomes', 'Normal Tomes'),
    CatalogEntry('Warrior Tome', 21801, 'Tomes', 'Normal Tomes'),
    CatalogEntry('Assassin Elitetome', 21786, 'Tomes', 'Elite Tomes'),
    CatalogEntry('Dervish Elitetome', 21793, 'Tomes', 'Elite Tomes'),
    CatalogEntry('Elementalist Elitetome', 21789, 'Tomes', 'Elite Tomes'),
    CatalogEntry('Mesmer Elitetome', 21787, 'Tomes', 'Elite Tomes'),
    CatalogEntry('Monk Elitetome', 21790, 'Tomes', 'Elite Tomes'),
    CatalogEntry('Necromancer Elitetome', 21788, 'Tomes', 'Elite Tomes'),
    CatalogEntry('Paragon Elitetome', 21795, 'Tomes', 'Elite Tomes'),
    CatalogEntry('Ranger Elitetome', 21792, 'Tomes', 'Elite Tomes'),
    CatalogEntry('Ritualist Elitetome', 21794, 'Tomes', 'Elite Tomes'),
    CatalogEntry('Warrior Elitetome', 21791, 'Tomes', 'Elite Tomes'),
    CatalogEntry('Lockpick', 22751, 'Keys', 'Core Keys'),
    CatalogEntry('Phantom Key', 5882, 'Keys', 'Core Keys'),
    CatalogEntry('Obsidian Key', 5971, 'Keys', 'Core Keys'),
    CatalogEntry('Ascalonian Key', 5966, 'Keys', 'Prophecies Keys'),
    CatalogEntry('Steel Key', 5967, 'Keys', 'Prophecies Keys'),
    CatalogEntry('Krytan Key', 5964, 'Keys', 'Prophecies Keys'),
    CatalogEntry('Maguuma Key', 5965, 'Keys', 'Prophecies Keys'),
    CatalogEntry('Elonian Key', 5960, 'Keys', 'Prophecies Keys'),
    CatalogEntry('Shiverpeak Key', 5962, 'Keys', 'Prophecies Keys'),
    CatalogEntry('Darkstone Key', 5963, 'Keys', 'Prophecies Keys'),
    CatalogEntry('Miners Key', 5961, 'Keys', 'Prophecies Keys'),
    CatalogEntry('Shing Jea Key', 6537, 'Keys', 'Factions Keys'),
    CatalogEntry('Canthan Key', 6540, 'Keys', 'Factions Keys'),
    CatalogEntry('Kurzick Key', 6535, 'Keys', 'Factions Keys'),
    CatalogEntry('Stoneroot Key', 6536, 'Keys', 'Factions Keys'),
    CatalogEntry('Luxon Key', 6538, 'Keys', 'Factions Keys'),
    CatalogEntry('Deep Jade Key', 6539, 'Keys', 'Factions Keys'),
    CatalogEntry('Forbidden Key', 6534, 'Keys', 'Factions Keys'),
    CatalogEntry('Istani Key', 15557, 'Keys', 'Nightfall Keys'),
    CatalogEntry('Kournan Key', 15559, 'Keys', 'Nightfall Keys'),
    CatalogEntry('Vabbian Key', 15558, 'Keys', 'Nightfall Keys'),
    CatalogEntry('Ancient Elonian Key', 15556, 'Keys', 'Nightfall Keys'),
    CatalogEntry('Margonite Key', 15560, 'Keys', 'Nightfall Keys'),
    CatalogEntry('Demonic Key', 19174, 'Keys', 'Nightfall Keys'),
    CatalogEntry('Bolt Of Cloth', 925, 'Materials', 'Common Materials'),
    CatalogEntry('Bone', 921, 'Materials', 'Common Materials'),
    CatalogEntry('Chitin Fragment', 954, 'Materials', 'Common Materials'),
    CatalogEntry('Feather', 933, 'Materials', 'Common Materials'),
    CatalogEntry('Granite Slab', 955, 'Materials', 'Common Materials'),
    CatalogEntry('Iron Ingot', 948, 'Materials', 'Common Materials'),
    CatalogEntry('Pile Of Glittering Dust', 929, 'Materials', 'Common Materials'),
    CatalogEntry('Plant Fiber', 934, 'Materials', 'Common Materials'),
    CatalogEntry('Scale', 953, 'Materials', 'Common Materials'),
    CatalogEntry('Tanned Hide Square', 940, 'Materials', 'Common Materials'),
    CatalogEntry('Wood Plank', 946, 'Materials', 'Common Materials'),
    CatalogEntry('Amber Chunk', 6532, 'Materials', 'Rare Materials'),
    CatalogEntry('Bolt Of Damask', 927, 'Materials', 'Rare Materials'),
    CatalogEntry('Bolt Of Linen', 926, 'Materials', 'Rare Materials'),
    CatalogEntry('Bolt Of Silk', 928, 'Materials', 'Rare Materials'),
    CatalogEntry('Deldrimor Steel Ingot', 950, 'Materials', 'Rare Materials'),
    CatalogEntry('Diamond', 935, 'Materials', 'Rare Materials'),
    CatalogEntry('Elonian Leather Square', 943, 'Materials', 'Rare Materials'),
    CatalogEntry('Fur Square', 941, 'Materials', 'Rare Materials'),
    CatalogEntry('Glob Of Ectoplasm', 930, 'Materials', 'Rare Materials'),
    CatalogEntry('Jadeite Shard', 6533, 'Materials', 'Rare Materials'),
    CatalogEntry('Leather Square', 942, 'Materials', 'Rare Materials'),
    CatalogEntry('Lump Of Charcoal', 922, 'Materials', 'Rare Materials'),
    CatalogEntry('Monstrous Claw', 923, 'Materials', 'Rare Materials'),
    CatalogEntry('Monstrous Eye', 931, 'Materials', 'Rare Materials'),
    CatalogEntry('Monstrous Fang', 932, 'Materials', 'Rare Materials'),
    CatalogEntry('Obsidian Shard', 945, 'Materials', 'Rare Materials'),
    CatalogEntry('Onyx Gemstone', 936, 'Materials', 'Rare Materials'),
    CatalogEntry('Roll Of Parchment', 951, 'Materials', 'Rare Materials'),
    CatalogEntry('Roll Of Vellum', 952, 'Materials', 'Rare Materials'),
    CatalogEntry('Ruby', 937, 'Materials', 'Rare Materials'),
    CatalogEntry('Sapphire', 938, 'Materials', 'Rare Materials'),
    CatalogEntry('Spiritwood Plank', 956, 'Materials', 'Rare Materials'),
    CatalogEntry('Steel Ingot', 949, 'Materials', 'Rare Materials'),
    CatalogEntry('Tempered Glass Vial', 939, 'Materials', 'Rare Materials'),
    CatalogEntry('Vial Of Ink', 944, 'Materials', 'Rare Materials'),
    CatalogEntry('Abnormal Seed', 442, 'Trophies', ''),
    CatalogEntry('Alpine Seed', 497, 'Trophies', ''),
    CatalogEntry('Amphibian Tongue', 27036, 'Trophies', ''),
    CatalogEntry('Ancient Eye', 464, 'Trophies', ''),
    CatalogEntry('Ancient Kappa Shell', 856, 'Trophies', ''),
    CatalogEntry('Archaic Kappa Shell', 850, 'Trophies', ''),
    CatalogEntry('Ashen Wurm Husk', 27059, 'Trophies', ''),
    CatalogEntry('Augmented Flesh', 826, 'Trophies', ''),
    CatalogEntry('Azure Crest', 844, 'Trophies', ''),
    CatalogEntry('Azure Remains', 496, 'Trophies', ''),
    CatalogEntry('Baked Husk', 433, 'Trophies', ''),
    CatalogEntry('Beetle Egg', 27066, 'Trophies', ''),
    CatalogEntry('Behemoth Hide', 1675, 'Trophies', ''),
    CatalogEntry('Behemoth Jaw', 465, 'Trophies', ''),
    CatalogEntry('Berserker Horn', 27046, 'Trophies', ''),
    CatalogEntry('Black Pearl', 841, 'Trophies', ''),
    CatalogEntry('Bleached Carapace', 449, 'Trophies', ''),
    CatalogEntry('Blob Of Ooze', 27067, 'Trophies', ''),
    CatalogEntry('Blood Drinker Pelt', 812, 'Trophies', ''),
    CatalogEntry('Bog Skale Fin', 443, 'Trophies', ''),
    CatalogEntry('Bone Charm', 811, 'Trophies', ''),
    CatalogEntry('Branch of Juni Berries', 19194, 'Trophies', ''),
    CatalogEntry('Bull Trainer Giant Jawbone', 1680, 'Trophies', ''),
    CatalogEntry('Celestial Essence', 855, 'Trophies', ''),
    CatalogEntry('Charr Carving', 423, 'Trophies', ''),
    CatalogEntry('Chromatic Scale', 27069, 'Trophies', ''),
    CatalogEntry('Chunk Of Drake Flesh', 19185, 'Trophies', ''),
    CatalogEntry('Cobalt Talon', 1609, 'Trophies', ''),
    CatalogEntry('Copper Crimson Skull Coin', 806, 'Trophies', ''),
    CatalogEntry('Copper Shilling', 1577, 'Trophies', ''),
    CatalogEntry('Corrosive Spider Leg', 518, 'Trophies', ''),
    CatalogEntry('Curved Mintaur Horn', 495, 'Trophies', ''),
    CatalogEntry('Dark Claw', 528, 'Trophies', ''),
    CatalogEntry('Dark Remains', 522, 'Trophies', ''),
    CatalogEntry('Decayed Orr Emblem', 504, 'Trophies', ''),
    CatalogEntry('Demonic Fang', 473, 'Trophies', ''),
    CatalogEntry('Demonic Relic', 1580, 'Trophies', ''),
    CatalogEntry('Demonic Remains', 476, 'Trophies', ''),
    CatalogEntry('Dessicated Hydra Claw', 454, 'Trophies', ''),
    CatalogEntry('Destroyer Core', 27033, 'Trophies', ''),
    CatalogEntry('Diamond Djinn Essence', 19186, 'Trophies', ''),
    CatalogEntry('Diessa Chalice', 24353, 'Trophies', ''),
    CatalogEntry('Dragon Root', 819, 'Trophies', ''),
    CatalogEntry('Dregde Charm', 27064, 'Trophies', ''),
    CatalogEntry('Dredge Incisor', 818, 'Trophies', ''),
    CatalogEntry('Dryder Web', 27070, 'Trophies', ''),
    CatalogEntry('Dull Carapace', 425, 'Trophies', ''),
    CatalogEntry('Dune Burrower Jaw', 447, 'Trophies', ''),
    CatalogEntry('Dusty Insect Carapace', 1588, 'Trophies', ''),
    CatalogEntry('Ebon Spider Leg', 463, 'Trophies', ''),
    CatalogEntry('Elder Kappa Shell', 837, 'Trophies', ''),
    CatalogEntry('Enchanted Lodestone', 431, 'Trophies', ''),
    CatalogEntry('Enchanted Vine', 834, 'Trophies', ''),
    CatalogEntry('Encrusted Lodestone', 451, 'Trophies', ''),
    CatalogEntry('Enslavement Stone', 532, 'Trophies', ''),
    CatalogEntry('Feathered Avicara Scalp', 498, 'Trophies', ''),
    CatalogEntry('Feathered Caromi Scalp', 444, 'Trophies', ''),
    CatalogEntry('Feathered Crest', 835, 'Trophies', ''),
    CatalogEntry('Feathered Scalp', 836, 'Trophies', ''),
    CatalogEntry('Fetid Carapace', 479, 'Trophies', ''),
    CatalogEntry('Fetid Mass', 1665, 'Trophies', ''),
    CatalogEntry('Fibrous Mandragor Root', 27051, 'Trophies', ''),
    CatalogEntry('Fiery Crest', 508, 'Trophies', ''),
    CatalogEntry('Fledglin Skree Wing', 1596, 'Trophies', ''),
    CatalogEntry('Flesh Reaver Morsel', 27062, 'Trophies', ''),
    CatalogEntry('Forest Minotaur Horn', 440, 'Trophies', ''),
    CatalogEntry('Forgotten Seal', 459, 'Trophies', ''),
    CatalogEntry('Forgotten Trinket Box', 825, 'Trophies', ''),
    CatalogEntry('Frigid Heart', 494, 'Trophies', ''),
    CatalogEntry('Frigid Mandragor Husk', 27042, 'Trophies', ''),
    CatalogEntry('Frosted Griffon Wing', 493, 'Trophies', ''),
    CatalogEntry('Frostfire Fang', 489, 'Trophies', ''),
    CatalogEntry('Frozen Wurm Husk', 27048, 'Trophies', ''),
    CatalogEntry('Fungal Root', 27061, 'Trophies', ''),
    CatalogEntry('Gargoyle Skull', 426, 'Trophies', ''),
    CatalogEntry('Geode', 1681, 'Trophies', ''),
    CatalogEntry('Giant Tusk', 1590, 'Trophies', ''),
    CatalogEntry('Glacial Stone', 27047, 'Trophies', ''),
    CatalogEntry('Gloom Seed', 523, 'Trophies', ''),
    CatalogEntry('Glowing Heart', 439, 'Trophies', ''),
    CatalogEntry('Gold Crimson Skull Coin', 807, 'Trophies', ''),
    CatalogEntry('Gold Doubloon', 1578, 'Trophies', ''),
    CatalogEntry('Golden Rin Relic', 24354, 'Trophies', ''),
    CatalogEntry('Golem Runestone', 27065, 'Trophies', ''),
    CatalogEntry('Grawl Necklace', 432, 'Trophies', ''),
    CatalogEntry('Gruesome Ribcage', 482, 'Trophies', ''),
    CatalogEntry('Gruesome Sternum', 475, 'Trophies', ''),
    CatalogEntry('Guardian Moss', 849, 'Trophies', ''),
    CatalogEntry('Hardened Hump', 435, 'Trophies', ''),
    CatalogEntry('Heket Tongue', 19199, 'Trophies', ''),
    CatalogEntry('Huge Jawbone', 492, 'Trophies', ''),
    CatalogEntry('Hunting Minotaur Horn', 1682, 'Trophies', ''),
    CatalogEntry('Iboga Petal', 19183, 'Trophies', ''),
    CatalogEntry('Icy Hump', 490, 'Trophies', ''),
    CatalogEntry('Icy Lodestone', 424, 'Trophies', ''),
    CatalogEntry('Igneous Hump', 510, 'Trophies', ''),
    CatalogEntry('Igneous Spider Leg', 505, 'Trophies', ''),
    CatalogEntry('Immolated Djinn Essence', 1620, 'Trophies', ''),
    CatalogEntry('Incubus Wing', 27034, 'Trophies', ''),
    CatalogEntry('Inscribed Shard', 1587, 'Trophies', ''),
    CatalogEntry('Insect Appendage', 1597, 'Trophies', ''),
    CatalogEntry('Insect Carapace', 1617, 'Trophies', ''),
    CatalogEntry('Intricate Grawl Necklace', 499, 'Trophies', ''),
    CatalogEntry('Iridescant Griffon Wing', 453, 'Trophies', ''),
    CatalogEntry('Ivory Troll Tusk', 445, 'Trophies', ''),
    CatalogEntry('Jade Bracelet', 809, 'Trophies', ''),
    CatalogEntry('Jade Mandible', 457, 'Trophies', ''),
    CatalogEntry('Jade Orb', 15940, 'Trophies', ''),
    CatalogEntry('Jotun Pelt', 27045, 'Trophies', ''),
    CatalogEntry('Jungle Skale Fin', 470, 'Trophies', ''),
    CatalogEntry('Jungle Troll Tusk', 471, 'Trophies', ''),
    CatalogEntry('Juvenile Termite Leg', 1598, 'Trophies', ''),
    CatalogEntry('Kappa Hatchling Shell', 838, 'Trophies', ''),
    CatalogEntry('Kappa Shell', 839, 'Trophies', ''),
    CatalogEntry('Keen Oni Talon', 847, 'Trophies', ''),
    CatalogEntry('Kirin Horn', 846, 'Trophies', ''),
    CatalogEntry('Kournan Pendant', 1582, 'Trophies', ''),
    CatalogEntry('Krait Skin', 27729, 'Trophies', ''),
    CatalogEntry('Kraken Eye', 843, 'Trophies', ''),
    CatalogEntry('Kurzick Bauble', 604, 'Trophies', ''),
    CatalogEntry('Lavastrider Appendage', 27058, 'Trophies', ''),
    CatalogEntry('Leathery Claw', 484, 'Trophies', ''),
    CatalogEntry('Losaru Mane', 448, 'Trophies', ''),
    CatalogEntry('Luminous Stone', 1660, 'Trophies', ''),
    CatalogEntry('Lustrous Stone', 1661, 'Trophies', ''),
    CatalogEntry('Luxon Pendant', 810, 'Trophies', ''),
    CatalogEntry('Maguuma Mane', 466, 'Trophies', ''),
    CatalogEntry('Mahgo Claw', 513, 'Trophies', ''),
    CatalogEntry('Maguuma Spider Web', 234, 'Trophies', ''),
    CatalogEntry('Mandragor Husk', 1668, 'Trophies', ''),
    CatalogEntry('Mandragor Root', 1686, 'Trophies', ''),
    CatalogEntry('Mandragor Swamproot', 1671, 'Trophies', ''),
    CatalogEntry('Mantid Pincer', 815, 'Trophies', ''),
    CatalogEntry('Mantid Ungula', 27054, 'Trophies', ''),
    CatalogEntry('Mantis Pincer', 829, 'Trophies', ''),
    CatalogEntry('Margonite Mask', 1581, 'Trophies', ''),
    CatalogEntry('Massive Jawbone', 452, 'Trophies', ''),
    CatalogEntry('Mergoyle Skull', 436, 'Trophies', ''),
    CatalogEntry('Minotaur Horn', 455, 'Trophies', ''),
    CatalogEntry('Modnir Mane', 27043, 'Trophies', ''),
    CatalogEntry('Molten Claw', 503, 'Trophies', ''),
    CatalogEntry('Molten Eye', 506, 'Trophies', ''),
    CatalogEntry('Molten Heart', 514, 'Trophies', ''),
    CatalogEntry('Mossy Mandible', 469, 'Trophies', ''),
    CatalogEntry('Mountain Root', 27049, 'Trophies', ''),
    CatalogEntry('Mountain Troll Tusk', 500, 'Trophies', ''),
    CatalogEntry('Moon Shell', 1009, 'Trophies', ''),
    CatalogEntry('Mummy Wrapping', 1583, 'Trophies', ''),
    CatalogEntry('Mursaat Token', 462, 'Trophies', ''),
    CatalogEntry('Naga Hide', 832, 'Trophies', ''),
    CatalogEntry('Naga Pelt', 833, 'Trophies', ''),
    CatalogEntry('Naga Skin', 848, 'Trophies', ''),
    CatalogEntry('Obsidian Burrower Jaw', 472, 'Trophies', ''),
    CatalogEntry('Oni Claw', 817, 'Trophies', ''),
    CatalogEntry('Oni Taloon', 831, 'Trophies', ''),
    CatalogEntry('Ornate Grawl Necklace', 487, 'Trophies', ''),
    CatalogEntry('Patch Of Simian Fur', 27038, 'Trophies', ''),
    CatalogEntry('Phantom Residue', 474, 'Trophies', ''),
    CatalogEntry('Pile Of Elemental Dust', 27050, 'Trophies', ''),
    CatalogEntry('Plague Idol', 805, 'Trophies', ''),
    CatalogEntry('Pulsating Growth', 824, 'Trophies', ''),
    CatalogEntry('Putrid Cyst', 827, 'Trophies', ''),
    CatalogEntry('Quetzal Crest', 27039, 'Trophies', ''),
    CatalogEntry('Rawhide Belt', 483, 'Trophies', ''),
    CatalogEntry('Red Iris Flower', 2994, 'Trophies', ''),
    CatalogEntry('Roaring Ether Claw', 1629, 'Trophies', ''),
    CatalogEntry('Rot Wallow Tusk', 842, 'Trophies', ''),
    CatalogEntry('Ruby Djinn Essence', 19187, 'Trophies', ''),
    CatalogEntry('Saurian Bone', 27035, 'Trophies', ''),
    CatalogEntry('Sentient Lodestone', 1619, 'Trophies', ''),
    CatalogEntry('Sentient Seed', 1601, 'Trophies', ''),
    CatalogEntry('Sentient Spore', 19198, 'Trophies', ''),
    CatalogEntry('Sentient Vine', 27041, 'Trophies', ''),
    CatalogEntry('Shadowy Husk', 526, 'Trophies', ''),
    CatalogEntry('Shadowy Remnants', 441, 'Trophies', ''),
    CatalogEntry('Shiverpeak Mane', 488, 'Trophies', ''),
    CatalogEntry('Shimmering Scale', 2566, 'Trophies', ''),
    CatalogEntry('Shriveled Eye', 446, 'Trophies', ''),
    CatalogEntry('Silver Bullion Coin', 1579, 'Trophies', ''),
    CatalogEntry('Silver Crimson Skull Coin', 808, 'Trophies', ''),
    CatalogEntry('Singed Gargoyle Skull', 480, 'Trophies', ''),
    CatalogEntry('Skale Claw', 1604, 'Trophies', ''),
    CatalogEntry('Skale Fang', 27055, 'Trophies', ''),
    CatalogEntry('Skale Fin', 19184, 'Trophies', ''),
    CatalogEntry('Skale Fin (pre-Searing)', 429, 'Trophies', ''),
    CatalogEntry('Skale Tooth', 1603, 'Trophies', ''),
    CatalogEntry('Skeletal Limb', 430, 'Trophies', ''),
    CatalogEntry('Skeleton Bone', 1605, 'Trophies', ''),
    CatalogEntry('Skelk Claw', 27040, 'Trophies', ''),
    CatalogEntry('Skelk Fang', 27060, 'Trophies', ''),
    CatalogEntry('Skree Wing', 1610, 'Trophies', ''),
    CatalogEntry('Skull Juju', 814, 'Trophies', ''),
    CatalogEntry('Soul Stone', 852, 'Trophies', ''),
    CatalogEntry('Spider Leg', 422, 'Trophies', ''),
    CatalogEntry('Spider Web', 224, 'Trophies', ''),
    CatalogEntry('Spiked Crest', 434, 'Trophies', ''),
    CatalogEntry('Stolen Provisions', 851, 'Trophies', ''),
    CatalogEntry('Stolen Shipment', 1424, 'Trophies', ''),
    CatalogEntry('Stolen Supplies', 37937, 'Trophies', ''),
    CatalogEntry('Stone Carving', 820, 'Trophies', ''),
    CatalogEntry('Stone Claw', 27057, 'Trophies', ''),
    CatalogEntry('Stone Grawl Necklace', 27053, 'Trophies', ''),
    CatalogEntry('Stone Horn', 816, 'Trophies', ''),
    CatalogEntry('Stone Summit Badge', 502, 'Trophies', ''),
    CatalogEntry('Stone Summit Emblem', 27044, 'Trophies', ''),
    CatalogEntry('Stormy Eye', 477, 'Trophies', ''),
    CatalogEntry('Superb Charr Carving', 27052, 'Trophies', ''),
    CatalogEntry('Tangled Seed', 468, 'Trophies', ''),
    CatalogEntry('Thorny Carapace', 467, 'Trophies', ''),
    CatalogEntry('Topaz Crest', 450, 'Trophies', ''),
    CatalogEntry('Truffle', 813, 'Trophies', ''),
    CatalogEntry('Umbral Eye', 519, 'Trophies', ''),
    CatalogEntry('Umbral Shell', 527, 'Trophies', ''),
    CatalogEntry('Umbral Skeletal Limb', 525, 'Trophies', ''),
    CatalogEntry('Unctuous Remains', 511, 'Trophies', ''),
    CatalogEntry('Undead Bone', 27974, 'Trophies', ''),
    CatalogEntry('Unnatural Seed', 428, 'Trophies', ''),
    CatalogEntry('Vaettir Essence', 27071, 'Trophies', ''),
    CatalogEntry('Venerable Mantid Pincer', 854, 'Trophies', ''),
    CatalogEntry('Vermin Hide', 853, 'Trophies', ''),
    CatalogEntry('War Supplies', 35121, 'Trophies', ''),
    CatalogEntry('Warden Horn', 822, 'Trophies', ''),
    CatalogEntry('Water Djinn Essence', 19189, 'Trophies', ''),
    CatalogEntry('Weaver Leg', 27037, 'Trophies', ''),
    CatalogEntry('White Mantle Badge', 461, 'Trophies', ''),
    CatalogEntry('White Mantle Emblem', 460, 'Trophies', ''),
    CatalogEntry('Worn Belt', 427, 'Trophies', ''),
    CatalogEntry('Confessors Orders', 35123, 'Reward Trophies', 'Prophecies'),
    CatalogEntry('Torment Gemstone', 21131, 'Reward Trophies', 'Nightfall'),
    CatalogEntry('Margonite Gemstone', 21128, 'Reward Trophies', 'Nightfall'),
    CatalogEntry('Stygian Gemstone', 21129, 'Reward Trophies', 'Nightfall'),
    CatalogEntry('Titan Gemstone', 21130, 'Reward Trophies', 'Nightfall'),
    CatalogEntry('Deldrimor Armor Remnant', 27321, 'Reward Trophies', 'Eye Of North'),
    CatalogEntry('Cloth Of The Brotherhood', 27322, 'Reward Trophies', 'Eye Of North'),
    CatalogEntry('Ministerial Commendation', 36985, 'Reward Trophies', 'Winds Of Change'),
    CatalogEntry('Lunar Token', 21833, 'Reward Trophies', 'Special Events'),
    CatalogEntry('Blessing Of War', 37843, 'Reward Trophies', 'Special Events'),
    CatalogEntry('Victory Token', 18345, 'Reward Trophies', 'Special Events'),
    CatalogEntry('Wayfarer Mark', 37765, 'Reward Trophies', 'Special Events'),
    CatalogEntry('Cc Shard', 556, 'Reward Trophies', 'Special Events'),
    CatalogEntry('Glob Of Frozen Ectoplasm', 21509, 'Reward Trophies', 'Special Events'),
    CatalogEntry('Trick-or-treat Bag', 28434, 'Reward Trophies', 'Special Events'),
    CatalogEntry('Map Piece (Bottom-Left)', 24631, 'Quest Items', 'Map Pieces'),
    CatalogEntry('Map Piece (Bottom-Right)', 24632, 'Quest Items', 'Map Pieces'),
    CatalogEntry('Map Piece (Top-Left)', 24629, 'Quest Items', 'Map Pieces'),
    CatalogEntry('Map Piece (Top-Right)', 24630, 'Quest Items', 'Map Pieces'),
    CatalogEntry('Dungeon Key', 25410, 'Quest Items', 'Keys'),
    CatalogEntry('Boss Key', 25416, 'Quest Items', 'Keys'),
    CatalogEntry('Cell Key', 15565, 'Quest Items', 'Keys'),
    CatalogEntry('Prison Key', 25413, 'Quest Items', 'Keys'),
    CatalogEntry('Diamond Key', 19175, 'Quest Items', 'Keys'),
    CatalogEntry('Ruby Key', 19177, 'Quest Items', 'Keys'),
    CatalogEntry('Sapphire Key', 19176, 'Quest Items', 'Keys'),
    CatalogEntry('Spectral Crystal (Bloodstone Cave)', 24635, 'Quest Items', 'Dungeon quest items'),
    CatalogEntry('Shimmering Essence (Bloodstone Cave)', 24633, 'Quest Items', 'Dungeon quest items'),
    CatalogEntry('Arcane Crystal Shard (Bloodstone Cave)', 24634, 'Quest Items', 'Dungeon quest items'),
    CatalogEntry('Exquisite Surmia Carving (Cathedral of Flames)', 24352, 'Quest Items', 'Dungeon quest items'),
    CatalogEntry('Hammer of Kathandrax (Catacombs of Kathandrax)', 22374, 'Quest Items', 'Dungeon quest items'),
    CatalogEntry('Prismatic Gelatinous Material (Ooze Pit)', 22375, 'Quest Items', 'Dungeon quest items'),
    CatalogEntry('Elemental Crystal Shard', 38302, 'Trophies', ''),
    CatalogEntry('Elemental Keystone', 38301, 'Quest Items', 'Keys'),
)


UNRESOLVED: tuple[UnresolvedEntry, ...] = (
    UnresolvedEntry('Animal Hide', 'Trophies'),
    UnresolvedEntry('Bleached Shell', 'Trophies'),
    UnresolvedEntry('Bonesnap Shell', 'Trophies'),
    UnresolvedEntry('Dark Flame Fang', 'Trophies'),
    UnresolvedEntry('Dregde Manifesto', 'Trophies'),
    UnresolvedEntry('Frozen Remnant', 'Trophies'),
    UnresolvedEntry('Frozen Shell', 'Trophies'),
    UnresolvedEntry('Gargantuan Jawbone', 'Trophies'),
    UnresolvedEntry('Ghostly Remains', 'Trophies'),
    UnresolvedEntry('Kuskale Claw', 'Trophies'),
    UnresolvedEntry('Leather Belt', 'Trophies'),
    UnresolvedEntry('Mandragor Carapace', 'Trophies'),
    UnresolvedEntry('Rinkhal Talon', 'Trophies'),
    UnresolvedEntry('Smoking Remains', 'Trophies'),
    UnresolvedEntry('Spiny Seed', 'Trophies'),
    UnresolvedEntry('Vampiric Fang', 'Trophies'),
)


_BY_MODEL_ID: dict[int, CatalogEntry] = {e.model_id: e for e in CATALOG}


def categories() -> list[str]:
    """Category names, in catalog order."""
    seen: dict[str, None] = {}
    for entry in CATALOG:
        seen.setdefault(entry.category, None)
    return list(seen)


def groups(category: str) -> list[str]:
    """Group names within a category, in catalog order. Empty when the category has no groups."""
    seen: dict[str, None] = {}
    for entry in CATALOG:
        if entry.category == category and entry.group:
            seen.setdefault(entry.group, None)
    return list(seen)


def in_category(category: str) -> list[CatalogEntry]:
    return [e for e in CATALOG if e.category == category]


def in_group(category: str, group: str) -> list[CatalogEntry]:
    return [e for e in CATALOG if e.category == category and e.group == group]


def by_model_id(model_id: int) -> CatalogEntry | None:
    return _BY_MODEL_ID.get(int(model_id))


def model_ids(category: str | None = None) -> set[int]:
    if category is None:
        return set(_BY_MODEL_ID)
    return {e.model_id for e in CATALOG if e.category == category}


def alphabetical_bands(entries) -> list[tuple[str, list[CatalogEntry]]]:
    """Band entries by first letter, sorted. The render-time replacement for Trophies' A...W data."""
    bands: dict[str, list[CatalogEntry]] = {}
    for entry in sorted(entries, key=lambda e: e.name.lower()):
        bands.setdefault(entry.name[:1].upper(), []).append(entry)
    return sorted(bands.items())
